### ISSUE TITLE
columnize is not a function due to async

### ISSUE THREAD

**Issue by monkecheese** [pressbooks/pressbooks-book#1]
I've run into an issue where, upon loading a Table of Contents page, the list of contents will render into one column.  When I check the javascript console, I get an error saying `$(...).columnize is not a function`, even though, in the network tab, both `columnizer.js` and `columnizer-load.js` are returning a 200 status.

When you reload the page, it almost always renders correctly and the javascript error goes away.

Looking at the codebase, it appears that in `pressbooks/themes-book/pressbooks-book/functions.php`, in a function called `pressbooks_async_scripts`, there is an array of script names that are then loaded asynchronously.  And in that array are the two aforementioned scripts.  When I remove them from this list, the problem seems to go away.  Though I imagine, they were added to that list to increase page load performance.

The other odd thing to note is that in the `wp_enqueue_script` for `columnizer-load`, `columnizer` is added as a dependency to that script, so Wordpress *should* be loading them in the right order.  Perhaps there's a different Wordpress "way" of dealing with async while preserving script dependency?

**Comment by monkecheese** [comment]
A potential solution might be to add a function with an array of scripts to be deferred until immediately after the DOM loads.  This way the scripts aren't blocking, and the scripts load in the correct order:

```
...
/* ------------------------------------------------------------------------ *
 * Defer loading for scripts with dependencies
 * ------------------------------------------------------------------------ */

function pressbooks_defer_scripts( $tag, $handle, $src ) {
	$defer = array(
		'columnizer',
		'columnizer-load',
	);

	if ( in_array( $handle, $defer ) ) {
		return "<script defer type='text/javascript' src='{$src}'></script>" . "\n";
	}

	return $tag;
}
add_filter( 'script_loader_tag', 'pressbooks_defer_scripts', 10, 3 );
...
```

**Comment by greatislander** [comment]
@monkecheese There's a PR for this. I just concatenated the two scripts so they're loaded as one now. Can you test? (Note: needs to be run in a Pressbooks 4.0-dev environment.)

**Comment by monkecheese** [comment]
Friday is the next day I have time, so I'll test then and get back to you.  Thanks!

**Comment by monkecheese** [comment]
This fix seems to work in my test instance.  :)  Thanks @greatislander!
