### ISSUE TITLE
/h5p-listing/ not including the [h5p id="1"]

### ISSUE THREAD

**Issue by kqzheng** [pressbooks/pressbooks-book#1114]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [McLuhan](http://github.com/pressbooks/pressbooks-book/releases/latest/), and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing the issue while using this book theme?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-book) to see if your bug or enhancement is already listed?

### Description

When adding"/h5p-listing/" at the end of the url to open the the H5P Activities List, the list doesn't include the H5P whose id="1".
See these books for example:

- https://kpu.pressbooks.pub/testkz/h5p-listing/
- https://opentextbc.ca/studentsuicideawareness/h5p-listing/

### Steps to Reproduce

1. Open a book in Pressbooks that contains H5P
2. Add /h5p-listing/ to the end of the books url to open the H5P Activities List

**Expected behavior:** 
The H5P Activities List shows all the H5P activities including the [h5p id="1"]

**Actual behavior:** 
The H5P Activities List starts with the [h5p id="2"] and not including the [h5p id="1"]

**Comment by SteelWagstaff** [comment]
Thanks for filing @kqzheng -- we'll look into this. Note for our dev team: the H5P page listing is generated here: https://github.com/pressbooks/pressbooks-book/blob/dev/page-h5p-listing.php

**Comment by tw77** [comment]
This can be replicated on Integrations:

<img width="700" alt="Screenshot 2022-10-12 at 6 25 17 AM" src="https://user-images.githubusercontent.com/44182629/195354787-3b27f81d-039f-4ffd-92df-9d963f4a2553.png">

On a book with just one H5P activity, [h5p id="1"] isn't listed despite being counted in the total number of activities.

**Comment by kqzheng** [comment]
Thanks Steel! @tw77 I wonder if H5P id="1" is showing up in your book now? Unfortunately, they are still not appearing in my books.

**Comment by kqzheng** [comment]
Oh sorry I didn't know that. Thanks again! @SteelWagstaff
