### ISSUE TITLE
I am seeing strange behaviour in Webbook TOC, can you please check if you see this too?

### ISSUE THREAD

**Issue by thomasdumm** [pressbooks/pressbooks-book#115]
### Prerequisites

_Check the boxes below by changing them from `[ ]` to `[x]`._

* [x] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [Pressbooks Book](http://github.com/pressbooks/pressbooks-book/releases/latest/), and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing the issue while using this book theme?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-book) to see if your bug or enhancement is already listed?

### Description

Even for simple books with 1 font-matter, 2 chapters and 1 backmatter the TOC of the webbook behaves strange:
- It does not update if the titles are changed
- the hierarchies are not right

#### Book Info

Book ID: 15
Book URL: http://localhost/wordpress/test/
Book Privacy: Public

#### Browser

Platform: OS X
Browser Name: Firefox
Browser Version: 58.0
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:58.0) Gecko/20100101 Firefox/58.0

#### WordPress Configuration

Network URL: http://localhost/wordpress/
Network Type: Subdirectory
Version: 4.9.4
Language: en_US
WP_ENV: developer
WP_DEBUG: Enabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 4.5.0
Book Theme: McLuhan
Book Theme Version: 2.0.0-beta.2
Root Theme: Aldine
Root Theme Version: 1.0.0-alpha.6

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

Pressbooks: 5.0.0-dev

#### Server Configuration

PHP Version: 7.1.12
MySQL Version: 5.6.38
Webserver Info: Apache/2.2.34 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.1.12 mod_ssl/2.2.34 OpenSSL/1.0.2j DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.24.0

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 256M
Upload Max Size: 32M
Post Max Size: 32M
Upload Max Filesize: 32M
Time Limit: 30
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: On (1)

#### PHP Extensions

OPcache: Disabled
XDebug: Disabled
cURL: Supported
cURL Version: 7.52.1
imagick: Not Installed
xsl: Installed

**Comment by thomasdumm** [comment]
![p1](https://user-images.githubusercontent.com/3658808/36155994-2749f898-10d6-11e8-8ec3-7d8382891635.jpg)
![p2](https://user-images.githubusercontent.com/3658808/36156002-29882b7a-10d6-11e8-8701-0a5dfdab816f.jpg)
![p3](https://user-images.githubusercontent.com/3658808/36156007-2bd69ff6-10d6-11e8-878d-3e31d0683956.jpg)

**Comment by thomasdumm** [comment]
different book to show the the strange indentation

![s1](https://user-images.githubusercontent.com/3658808/36159154-53ab1ab8-10de-11e8-8ba0-e395f4d83451.jpg)

**Comment by thomasdumm** [comment]
Organize page:

![s2](https://user-images.githubusercontent.com/3658808/36159282-9d63603e-10de-11e8-82e4-c5be1aa61425.jpg)

**Comment by greatislander** [comment]
This has been fixed in recent commits; I have not released a new version yet. See:

https://github.com/pressbooks/pressbooks-book/commit/2e6b08b5f0bca5fabfcd5495aa8a7441350c0327

https://github.com/pressbooks/pressbooks-book/commit/0d9412b0f98a96ac089895a158e808c134414e3d

https://github.com/pressbooks/pressbooks-book/commit/9982d5d55f9ab584f7e86058e21da2e2921a0e71
