### ISSUE TITLE
It would be nice if clicking in the webbook TOC on the small triangle would open the toc with focus on the current chapter

### ISSUE THREAD

**Issue by thomasdumm** [pressbooks/pressbooks-book#116]
### Prerequisites

_Check the boxes below by changing them from `[ ]` to `[x]`._

* [x] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [Pressbooks Book](http://github.com/pressbooks/pressbooks-book/releases/latest/), and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing the issue while using this book theme?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-book) to see if your bug or enhancement is already listed?

### Description
It would be nice if clicking in the webbook TOC on the small triangle would open the TOC with focus on the current chapter. See printscreen.

![u1](https://user-images.githubusercontent.com/3658808/36208705-fd672eaa-1199-11e8-80f7-054a72cc7032.jpg)

**Comment by greatislander** [comment]
See also: https://github.com/pressbooks/ideas/issues/7

**Comment by colomet** [comment]
https://discourse.pressbooks.org/t/possibility-of-hiding-showing-content-within-a-chapter/327

**Comment by greatislander** [comment]
@colomet Did you read this issue? The discourse link you just posted has absolutely nothing to do with it.

**Comment by colomet** [comment]
I do not think it works.

If i'm in a chapter, and I open the table of contents, all the tabs are close.
