### ISSUE TITLE
Update multiple French translations

### ISSUE THREAD

**Issue by tw77** [pressbooks/pressbooks-book#1184]
Pointed out by ÉTS (for internal reference https://pressbooks.zendesk.com/agent/tickets/18820):

1. On the Book Info page, there is a missing uppercase letter for 'identificateur' https://github.com/pressbooks/pressbooks-book/blob/b202c467147bd4467efe52ff1fa3eeac1867175f/languages/fr_FR.po#L337
2. Also on that page, 'Print ISBN' should be 'NINL du livre imprimé' https://github.com/pressbooks/pressbooks-book/blob/b202c467147bd4467efe52ff1fa3eeac1867175f/languages/fr_FR.po#L344

There is a third issue where the Contributor listing generated at the end of a page says with 'ABOUT THEAUTEUR' instead of 'À propos de l’auteur':
<img width="210" alt="Screenshot 2023-10-31 at 12 54 24 PM" src="https://github.com/pressbooks/pressbooks-book/assets/44182629/9ad8783b-4c80-4360-ab15-9b215c71b2b1">
but I'm not sure where the code for this lives. I did find an 
'À propos de l'auteur' string in Transifex at https://app.transifex.com/pressbooks/pressbooks/viewstrings/#fr/pressbooks/334889495?q=text%3A'about+the+author'

**Update on third issue:** A different client suggested a different string for this one; Mich has a better string in mind that is gender inclusive and also points to additional French translations that would make sense to submit.

**Comment by tw77** [comment]
Noting here that we'd like to discuss Transifex process with Steel to fully understand what's required to submit multiple changes (changes that are more extensive than the few indicated in the original ticket here)

**Comment by tw77** [comment]
Added short update to original post here.

**Comment by SteelWagstaff** [comment]
Code for displaying 'About the Authors' lives here: https://github.com/pressbooks/pressbooks/blob/b014607c4d3c5da3947c516f3e70ad3ad72d1fc8/inc/modules/export/namespace.php#L333

**Comment by SteelWagstaff** [comment]
I've updated the transifex file for the first two proposed changes. Will be included in next release of pressbooks-book. I've also opened PRs to improve the localization string for 'About the author(s)'. Once merged, these strings will be updated in both Pressbooks and pressbooks-book. We'll then be able to provide improved translations for the singular and plural forms in both locations.

**Comment by SteelWagstaff** [comment]
PRs have been merged and .pot files have been updated in both repos. Will check Transifex to make sure strings are available later today.

**Comment by SteelWagstaff** [comment]
Transifex .pot files aren't being updated automatically. We worked on this in the past: https://github.com/pressbooks/ideas/issues/283, but it is broken. Pot files are updated in our repos, but not in Transifex:
![Screenshot from 2023-12-14 12-11-01](https://github.com/pressbooks/pressbooks-book/assets/13485451/c2a1e36e-a0e2-4dfd-8a0a-7bd4cd06b0ef)
![Screenshot from 2023-12-14 12-11-18](https://github.com/pressbooks/pressbooks-book/assets/13485451/e1ed4eef-0ea8-464a-a19f-0a267172863b)

I will try to fix/resolve this as soon as I'm able.

**Comment by SteelWagstaff** [comment]
Manually updated transifex .pot files and provided initial French translations for all untranslated strings in pressbooks & pressbooks-book. Will show Mich how to improve translations on Monday.

**Comment by SteelWagstaff** [comment]
Mich has received Transifex permissions and training on updating translations. They will make plan for better gender inclusivity in French in new year.
