### ISSUE TITLE
Part pages are missing back/forward navigation

### ISSUE THREAD

**Issue by beckej13820** [pressbooks/pressbooks-book#140]
### Prerequisites

_Check the boxes below by changing them from `[ ]` to `[x]`._

* [x] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [X] Are you running the [Pressbooks 5.0]
(http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [Pressbooks Book](http://github.com/pressbooks/pressbooks-book/releases/latest/), and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [X] Are you experiencing the issue while using this book theme?
* [X] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-book) to see if your bug or enhancement is already listed?

### Description

If you navigate to one of the Part pages from a link, there are no forward and backward buttons.

### Steps to Reproduce

1. Go to a books with Parts like an openstax textbook that organizes each chapter in a part, and then creates chapter sections using pressbooks chapters. Example) x
http://oer.ed-beck.com/openstaxchemistry/part/essential-ideas/

2. Notice that there are no forward and back icons.
![screen shot 2018-03-03 at 5 19 05 pm](https://user-images.githubusercontent.com/29982981/36939959-52357bc8-1f08-11e8-8854-bce16db52c8b.png)

**Expected behavior:** I'd expect a forward button that would bring me to the first chapter in this part, and a back button that would bring me to the last section of the previous part.

**Actual behavior:** You can only navigate from this page using the table of contents dropdown.

#### Book Info

Book ID: 6
Book URL: http://oer.ed-beck.com/openstaxchemistry/
Book Privacy: Public

#### Browser

Platform: OS X
Browser Name: Chrome
Browser Version: 64.0.3282.186
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36

#### WordPress Configuration

Network URL: http://oer.ed-beck.com/
Network Type: Subdirectory
Version: 4.9.4
Language: en_US
WP_ENV: Not set
WP_DEBUG: Enabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 5.0.0
Book Theme: McLuhan
Book Theme Version: 2.0.0
Root Theme: Aldine
Root Theme Version: 1.0.0-RC.2

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Not Installed
PrinceXML: Not Installed
Saxon-HE: Not Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

Candela LTI: 0.1
Candela Thin Exports: 0.1
Hypothesis: 0.5.0
LTI: 0.1
mPDF for Pressbooks: 3.1.0
Pressbooks: 5.0.0
Textbooks for Pressbooks: 4.0.0

#### Inactive Plugins

Akismet Anti-Spam: 4.0.3
CC Export for Pressbooks: 0.2.0
Hello Dolly: 1.6
Wp Show Site ID: 1.0.0

#### Server Configuration

PHP Version: 7.0.25-0ubuntu0.16.04.1
MySQL Version: 5.7.21
Webserver Info: Apache/2.4.18 (Ubuntu)

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 500M
Upload Max Size: 2000M
Post Max Size: 8M
Upload Max Filesize: 2000M
Time Limit: 30
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: On (1)

#### PHP Extensions

OPcache: Zend
XDebug: Disabled
cURL: Not Supported
imagick: Not Installed
xsl: Installed

**Comment by greatislander** [comment]
Thanks for reporting, @beckej13820. Looks like parts with readable content have been left out of the navigation order for a very long time. I've fixed this in pressbooks/pressbooks#1136.
