### ISSUE TITLE
Add Fluid Project's User Interface Options to webbook

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks-book#16]
### Description

See:

https://github.com/pressbooks/pressbooks/issues/489
https://github.com/fluid-project/uio-wordpress-plugin

### Steps to Reproduce

Not applicable.

### System Information

Book Theme: Pressbooks Book
Pressbooks: 4.0.0-dev
WordPress: 4.8.0
PHP: 7.1

**Comment by greatislander** [comment]
https://wiki.fluidproject.org/display/docs/Working+With+A+Preferences+Editor+On+Your+Site

**Comment by SteelWagstaff** [comment]
The Fluid Project does not appear to be actively developed or maintained. Great idea in concept though.
