### ISSUE TITLE
 EPUB/MOBI: TOC styling updates

### ISSUE THREAD

**Issue by dannylonglegs** [pressbooks/pressbooks-book#205]
### Prerequisites

* [ x Can you reproduce the behavior you wish to address with [all plugins except Pressbooks deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x ] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [Pressbooks Book](http://github.com/pressbooks/pressbooks-book/releases/latest/), the latest version of [this book theme](http://github.com/pressbooks/pressbooks-book/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x ] Are you experiencing the issue while using this book theme?
* [ x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-book) to see if your bug or enhancement is already listed?

### Description

- [x] Add top margin to TOC front matter titles
- [x] Add top margin to TOC chapter titles
- [x] Add TOC page margins
- [x] TOC chapter subtitle text-transform: Set to Italic
- [x] MOBI: TOC chapter title font-family needs to be changed

### Steps to Reproduce

1. Navigate to TOC on EPUB and MOBI and compare 'Before' and 'After' versions

**Comment by greatislander** [comment]
Fixed in pressbooks/pressbooks#1224.
