### ISSUE TITLE
Invalid argument supplied for foreach() in

### ISSUE THREAD

**Issue by thomasdumm** [pressbooks/pressbooks-book#216]
### Prerequisites

* [ ] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [Pressbooks Book](http://github.com/pressbooks/pressbooks-book/releases/latest/), the latest version of [this book theme](http://github.com/pressbooks/pressbooks-book/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing the issue while using this book theme?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-book) to see if your bug or enhancement is already listed?

### Description

The webbook footer shows the following warning message:

Notice
: Undefined index: parts in
/Applications/MAMP/htdocs/wordpress/wp-content/themes/pressbooks-book/inc/helpers/namespace.php
on line
373

Warning
: Invalid argument supplied for foreach() in
/Applications/MAMP/htdocs/wordpress/wp-content/themes/pressbooks-book/inc/helpers/namespace.php
on line
373

#### Book Info

Book ID: 16
Book URL: http://localhost/wordpress/pwlo00117r4/
Book Privacy: Public

#### Browser

Platform: OS X
Browser Name: Firefox
Browser Version: 60.0
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:60.0) Gecko/20100101 Firefox/60.0

#### WordPress Configuration

Network URL: http://localhost/wordpress/
Network Type: Subdirectory
Version: 4.9.5
Language: en_US
WP_ENV: developer
WP_DEBUG: Enabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 5.3.0
Book Theme: McLuhan
Book Theme Version: 2.3.0
Root Theme: Aldine
Root Theme Version: 1.3.0

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

Hypothesis: 0.5.0
Pressbooks: 5.3.0

#### Server Configuration

PHP Version: 7.2.1
MySQL Version: 5.6.38
Webserver Info: Apache/2.2.34 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.2.1 mod_ssl/2.2.34 OpenSSL/1.0.2j DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.24.0

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 256M
Upload Max Size: 32M
Post Max Size: 8M
Upload Max Filesize: 32M
Time Limit: 30
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: On (1)

#### PHP Extensions

OPcache: Disabled
XDebug: Disabled
cURL: Supported
cURL Version: 7.52.1
imagick: Not Installed
xsl: Installed

**Comment by thomasdumm** [comment]
![undefined_index](https://user-images.githubusercontent.com/3658808/40100236-888510d4-58e3-11e8-8f79-0bc57b24483a.jpg)

**Comment by thomasdumm** [comment]
This happens only for 1 of the 3 books I have in my local Pressbooks. So if the warning does not ring a bell, please just close this issue.

**Comment by greatislander** [comment]
@thomasdumm Where was the book in question cloned from? Another book in your local development network?

**Comment by thomasdumm** [comment]
a while ago from https://delivros.pressbooks.pub

**Comment by greatislander** [comment]
@thomasdumm Is the original content still there and publicly accessible? This error seems to be a result of your Pressbooks install not being able to load the table of contents from the REST API of the source book.

**Comment by thomasdumm** [comment]
https://delivros.pressbooks.pub/pwlo00117r4
I checked that license and visibility allow cloning.

**Comment by thomasdumm** [comment]
I cloned the book again and do not see the issue any more. So either there was an issue with the cloning function at the time I cloned the book or during clonig something went wrong.

**Comment by thomasdumm** [comment]
not reproducable
