### ISSUE TITLE
Comparison tool feedback

### ISSUE THREAD

**Issue by thomasdumm** [pressbooks/pressbooks-book#217]
### Prerequisites

* [ ] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [Pressbooks Book](http://github.com/pressbooks/pressbooks-book/releases/latest/), the latest version of [this book theme](http://github.com/pressbooks/pressbooks-book/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing the issue while using this book theme?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-book) to see if your bug or enhancement is already listed?

### Description

The comparison tool works nicely! The following this popped up when I had a quick look at the  cloned *not edited* Pressbooks user guide:

- It looks like in some occasions spaces get converted into non-breaking spaces during cloning.  Or something else is happening. I do not really see what is causing the added nbsp.
- Breaking-Tags (br) are shown as differences
- All paragraph tags are shown as difference. 
- During cloning "prettify" (indent of tags) seems to be lost

The first two items might have something to to with the encoding of special characters?

![compare](https://user-images.githubusercontent.com/3658808/40102132-f70528a4-58e9-11e8-8c49-5e2a507bdfef.jpg)

![compare2](https://user-images.githubusercontent.com/3658808/40102253-4e17ca7a-58ea-11e8-8c08-6a06c7b9db13.jpg)

![compare2](https://user-images.githubusercontent.com/3658808/40166660-6210fd5a-59bf-11e8-84f6-17da5876bfd9.jpg)

#### Book Info

Book ID: 17
Book URL: http://localhost/wordpress/guide/
Book Privacy: Public

#### Browser

Platform: OS X
Browser Name: Firefox
Browser Version: 60.0
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:60.0) Gecko/20100101 Firefox/60.0

#### WordPress Configuration

Network URL: http://localhost/wordpress/
Network Type: Subdirectory
Version: 4.9.5
Language: en_US
WP_ENV: developer
WP_DEBUG: Enabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 5.3.0
Book Theme: McLuhan
Book Theme Version: 2.3.0
Root Theme: Aldine
Root Theme Version: 1.3.0

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

Hypothesis: 0.5.0
Pressbooks: 5.3.0

#### Server Configuration

PHP Version: 7.2.1
MySQL Version: 5.6.38
Webserver Info: Apache/2.2.34 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.2.1 mod_ssl/2.2.34 OpenSSL/1.0.2j DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.24.0

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 256M
Upload Max Size: 32M
Post Max Size: 8M
Upload Max Filesize: 32M
Time Limit: 30
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: On (1)

#### PHP Extensions

OPcache: Disabled
XDebug: Disabled
cURL: Supported
cURL Version: 7.52.1
imagick: Not Installed
xsl: Installed

**Comment by greatislander** [comment]
Closed in lieu of https://github.com/pressbooks/pressbooks/issues/1283.

**Comment by greatislander** [comment]
Fixed in #248 and pressbooks/pressbooks#1312.
