### ISSUE TITLE
Standard element translations not appearing in webbook since 1.9.0 release

### ISSUE THREAD

**Issue by zwhpressbooks** [pressbooks/pressbooks-book#22]
### Prerequisites

_Check the boxes below by changing them from `[ ]` to `[x]`._

* [x] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [Pressbooks Book](http://github.com/pressbooks/pressbooks-book/releases/latest/), and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing the issue while using this book theme?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-book) to see if your bug or enhancement is already listed?

### Description

Since 1.9.0 release, standard elements on webbook homepage & reading interface remain in English when another language is selected in "Book Info". Translations are confirmed present in Transifex. PDF & ebook unaffected.

Reported by a client on several books (can share URLs in Slack if need be, set to French) but confirmed on [test book](zwhtestspace.pressbooks.com).

### Steps to Reproduce

1. Change book language away from English (e.g. French/Spanish/German)
2. Navigate to webbook
3. Check standard elements (e.g. 'Read' button, 'Book Description', 'Table of Contents')

**Expected behavior:** Standard elements should appear in active book language

**Actual behavior:** Standard elements appear in English

### System Information

Let me know if you need this from client book(s).

**Comment by greatislander** [comment]
@zwhpressbooks Not a bug. A bunch of strings were translated AFTER the release—my guess is that these French ones came in after Wednesday. Will do a minor release with more translations tomorrow.

**Comment by greatislander** [comment]
(Thanks for letting me know, though! I don't get notifications when new strings are translated. Note, should look into that. 🙃)

**Comment by greatislander** [comment]
D'oh.

> Unlike plugin language files, a name like my_theme-de_DE.mo will NOT work. Although plugin language files allow you to specify the text-domain in the filename, this will NOT work with themes. Language files for themes should include the language shortcut ONLY.
