### ISSUE TITLE
Footnotes on Headings have inconsistent behaviors across formats.

### ISSUE THREAD

**Issue by beckej13820** [pressbooks/pressbooks-book#238]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [Pressbooks Book](http://github.com/pressbooks/pressbooks-book/releases/latest/), the latest version of [this book theme](http://github.com/pressbooks/pressbooks-book/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing the issue while using this book theme?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-book) to see if your bug or enhancement is already listed?

### Description

If you have a footnote on a section that isn't a paragraph like an H1, H2, or H3, the footnote is exported at H1, H2, or H3 size in PDF exports using Prince.

On the ebook versions, if a footnote appears on H1 with two level table of content turned on, the entire footnote will appear in the table of contents both on the webpage and in exports.

### Steps to Reproduce

1. Create a footnote using the shortcodes on a H1
2. When two level table of contents is turned on, check to see that the entire footnote, including the shortcode appears in the table of contents on the book homepage.
3. Export to using PrinceXML and see that the footnote appears oversized in the footnote area.

**Expected behavior:** I'd expect the footnote to be ignored in the table of contents areas, and the number and footnote only displayed in chapter.

**Actual behavior:** see screenshots
Appears on homepage
<img width="476" alt="screen shot 2018-07-19 at 8 51 56 pm" src="https://user-images.githubusercontent.com/29982981/42977664-840b2396-8b96-11e8-830f-53c60c0e4dae.png">
In Print PDF exports, footnote texts appears as H1 size in exports
<img width="441" alt="screen shot 2018-07-19 at 8 48 26 pm" src="https://user-images.githubusercontent.com/29982981/42977672-8f3c0a82-8b96-11e8-8825-c25ed617878c.png">
In Epub3 exports appears as expected in text
<img width="902" alt="screen shot 2018-07-19 at 8 48 12 pm" src="https://user-images.githubusercontent.com/29982981/42977714-ce75c3fa-8b96-11e8-993d-2c0f73cf57a4.png">

#### Book Info

Book ID: 28
Book URL: https://oer.ed-beck.com/programmingforproblemsolving/
Book Privacy: Public

#### Browser

Platform: OS X
Browser Name: Chrome
Browser Version: 67.0.3396.99
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

#### WordPress Configuration

Network URL: http://oer.ed-beck.com/
Network Type: Subdirectory
Version: 4.9.7
Language: en_US
WP_ENV: production
WP_DEBUG: Disabled
Memory Limit: 5000M

#### Pressbooks Configuration

Version: 5.4.1
Book Theme: McLuhan
Book Theme Version: 2.4.1
Root Theme: Aldine
Root Theme Version: 1.4.0

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

GitHub Updater: 8.2.0
Openstax Import for Pressbooks: 1.2.1
Pressbooks: 5.4.1
Pressbooks LTI Provider: 1.0.0
Pressbooks Stats: 1.4.1
Really Simple SSL: 3.0.3

#### Inactive Plugins

Akismet Anti-Spam: 4.0.8
Candela Links: 0.1
Candela LTI: 0.1
Candela Thin Exports: 0.1
CC Export for Pressbooks: 0.2.3
H5P: 1.10.3
Hello Dolly: 1.6
Hypothesis: 0.5.0
LTI: 0.1
Textbooks for Pressbooks: 4.1.2
WP QuickLaTeX: 3.8.4
Wp Show Site ID: 1.0.1

#### Server Configuration

PHP Version: 7.0.30-0ubuntu0.16.04.1
MySQL Version: 5.7.22
Webserver Info: Apache/2.4.18 (Ubuntu)

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 5000M
Upload Max Size: 2000M
Post Max Size: 2000M
Upload Max Filesize: 2000M
Time Limit: 30
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: N/A

#### PHP Extensions

OPcache: Zend
XDebug: Disabled
cURL: Supported
cURL Version: 7.47.0
imagick: Installed
xsl: Installed

**Comment by mcgratay** [comment]
While the shortcode doesn't display in the table of contents, the footnote number still does. This is an improvement on the original but still worth noting. 

![Screen Shot 2019-05-22 at 7 08 22 PM](https://user-images.githubusercontent.com/39064028/58214923-97e0bb80-7cc5-11e9-9b92-60fcfc6782a1.png)

**Comment by mcgratay** [comment]
Footnotes on headings styled in italics display in italics 
![Screen Shot 2019-05-22 at 7 22 28 PM](https://user-images.githubusercontent.com/39064028/58215271-138f3800-7cc7-11e9-8aff-a595e5c43f95.png)

**Comment by dannylonglegs** [comment]
@mcgratay is the footnote number in the table of contents on web?

**Comment by mcgratay** [comment]
Resolved.
