### ISSUE TITLE
Images without captions will not center without additional CSS

### ISSUE THREAD

**Issue by josieg** [pressbooks/pressbooks-book#252]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [Pressbooks Book](http://github.com/pressbooks/pressbooks-book/releases/latest/), the latest version of [this book theme](http://github.com/pressbooks/pressbooks-book/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing the issue while using this book theme?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-book) to see if your bug or enhancement is already listed?

### Description
All images that do not have captions will appear left aligned in the web book and all export formats, regardless of the alignment that was actually given to them.  We found this issue on the Open Textbook theme, but behaviour also appears with the McLuhan theme.

I am able to fix this problem by adding the following CSS to the Custom styles for the web, PDF, and eBook. (However, it would be nice if adding CSS wasn't necessary.):

.front-matter img, .part img, .chapter img, .back-matter img {
    display: block;
    height: auto;
    margin-left: auto;
    margin-right: auto;
    max-width: 100%;
    padding: 0;
    page-break-inside: avoid !important;
    prince-image-resolution: 135dpi; } 

### Steps to Reproduce

1. Add an image to a chapter. Do not add a caption.
2. Center the image. The image appears centered in the editor view.
3. Look at the image in the web book, PDF, and ebook files. The image will be left aligned.

**Expected behavior:**
I expect the image to appear aligned how I have set it in all export formats. It should match the appearance in the visual editor.  

**Actual behavior:** 
All images without captions will appear left aligned in all formats, regardless of the alignment that is selected for them.

#### Book Info

Book ID: 500
Book URL: https://pressbooks.bccampus.ca/abookfortestingprod/
Book Privacy: Public

#### Browser

Platform: Windows
Browser Name: Chrome
Browser Version: 68.0.3440.106
User Agent String: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

#### WordPress Configuration

Network URL: http://pressbooks.bccampus.ca/
Network Type: Subdirectory
Version: 4.9.7
Language: en_US
WP_ENV: Not set
WP_DEBUG: Enabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 5.4.5
Book Theme: Open Textbooks
Book Theme Version: 2.1.4
Root Theme: Aldine
Root Theme Version: 1.4.1

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

bcc new user notify: 0.0.1
BC Post-Secondary Validator: 1.0.0
CC Export for Pressbooks: 0.2.4
f5 Force SSL: 1.0.0
iThemes Security: 7.0.4
Openstax Import for Pressbooks: 1.2.4
Pressbooks: 5.4.5
Pressbooks Stats: 1.4.0
Textbooks for Pressbooks: 4.2.0
WP-Piwik: 1.0.19

#### Book Active Plugins

H5P: 1.10.3
WP QuickLaTeX: 3.8.4

#### Inactive Plugins

Akismet Anti-Spam: 4.0.8
Candela Citation: 0.2.2
mPDF for Pressbooks: 3.2.1

#### Server Configuration

PHP Version: 7.1.20
MySQL Version: 5.5.5
Webserver Info: Apache

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 512M
Upload Max Size: 500M
Post Max Size: 500M
Upload Max Filesize: 500M
Time Limit: 60
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: N/A

#### PHP Extensions

OPcache: Disabled
XDebug: Disabled
cURL: Supported
cURL Version: 7.19.7
imagick: Installed
xsl: Installed

**Comment by dannylonglegs** [comment]
Might have something to do with this function: https://github.com/pressbooks/pressbooks/blob/d84da56f61dc3774730daf57980bdbfa7976730f/inc/media/namespace.php#L63

**Comment by mcgratay** [comment]
Resolved 👍
