### ISSUE TITLE
 Enable Social Media Breaks Mobile Layout

### ISSUE THREAD

**Issue by connerbw** [pressbooks/pressbooks-book#28]
### Prerequisites

_Check the boxes below by changing them from `[ ]` to `[x]`._

* [X] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [X] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [Pressbooks Book](http://github.com/pressbooks/pressbooks-book/releases/latest/), and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [X] Are you experiencing the issue while using this book theme?
* [X] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-book) to see if your bug or enhancement is already listed?

### Description

When I enabled "Add buttons to cover page and each chapter so that readers may share links to your book through social media: Facebook, Twitter, Google+" the layout is broken on my Android (Moto E, Chrome)

Tested in Luther (and Asimov Color)

### Steps to Reproduce

1. Theme Options -> Web Options -> Enable Social Media
2. Navigate to a page on an Android (or emulate in Chrome)

**Expected behavior:** [What you expected to happen]

![without-social-media-buttons](https://user-images.githubusercontent.com/812192/29297433-eb364aaa-812e-11e7-8bdf-292df9c40c56.PNG)

**Actual behavior:** [What actually happened]

![with-social-media-buttons](https://user-images.githubusercontent.com/812192/29297432-eb229410-812e-11e7-99da-c3f649825358.PNG)

### System Information

Using a private test book for tests: https://dactest.pressbooks.com/front-matter/introduction/

**Comment by greatislander** [comment]
Done.

**Comment by connerbw** [comment]
In Textopress:

With Social Buttons, without comments:
![ok](https://user-images.githubusercontent.com/812192/29433662-231ad850-836e-11e7-9de6-ab140cab24ca.png)

With Social Buttons, with comments:
![off](https://user-images.githubusercontent.com/812192/29433663-2330197c-836e-11e7-8889-e715e36719b8.PNG)

The second one is still a bit off.

**Comment by greatislander** [comment]
I'm seeing this on Textopress right now:

<img width="400" alt="screen shot 2017-08-18 at 10 01 12 am" src="https://user-images.githubusercontent.com/605361/29459959-4d6bcef0-83fc-11e7-8f6d-7818eef7b7fc.png">

<img width="400" alt="screen shot 2017-08-18 at 10 01 45 am" src="https://user-images.githubusercontent.com/605361/29459962-4f2816ea-83fc-11e7-90d1-6bd3276025b6.png">

Is it still not appearing properly for you, @connerbw?

**Comment by connerbw** [comment]
@greatislander 

If I drag and drop the edges of my browser to the smallest possible size it's fine. 

The problem happens in device mode ( in Chrome, I do CTRL+SHIFT+J -> CTRL+SHIFT+M to activate it )

Hope this helps.

**Comment by greatislander** [comment]
Set `max-width: 100vw;` and it seems to be working for me now.

**Comment by connerbw** [comment]
Works for me.
