### ISSUE TITLE
Add support for <!--nextpage--> pagination

### ISSUE THREAD

**Issue by connerbw** [pressbooks/pressbooks-book#34]
### Prerequisites

_Check the boxes below by changing them from `[ ]` to `[x]`._

* [X] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [X] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [Pressbooks Book](http://github.com/pressbooks/pressbooks-book/releases/latest/), and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [X] Are you experiencing the issue while using this book theme?
* [X] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-book) to see if your bug or enhancement is already listed?

### Description

Add support for `<!--nextpage-->` so that long chapters can be broken up into smaller parts in web books.

### Technical Info

Info:
https://codex.wordpress.org/Styling_Page-Links

Code is in `\WP_Query::setup_postdata()` WordPress splits on `<!-- nextpage -->` then creates globals `$pages (array), $multipage (bool), $more (string), $numpages (int)`

`get_the_content()` already has code that deals with `$pages, $multipage` so it might already be working, without styling?

To investigate.

**Comment by connerbw** [comment]
I did some testing. It's `<!--nextpage-->` not `<!-- nextpage -->` (no spaces)

Split works. Pagination... not yet.

**Comment by connerbw** [comment]
Fixed in https://github.com/pressbooks/pressbooks-book/commit/9784ce96f3a808d4dfad4c2ee9a3ad32ae4a41c8

**Comment by greatislander** [comment]
Usage, for testing: switch to text editor, insert `<!--nextpage-->` wherever you want a break.
