### ISSUE TITLE
Hypothesis visibility & client toggle bugs

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks-book#392]
### Description

Following the release of our new Hypothesis window pane resizing feature, users are experiencing some strange behavior when they try to click annotations to expand/contract them. First, annotations are generally invisible when visitors first load the page, even though the 'Show Highlights' icon in the hypothesis client appears to be in visible state. If a user clicks the 'Show Highlights' icon, the highlights do become visible and the pane then expands as expected when a user clicks on a particular annotation. Clicking on the annotation again does not collapse the annotation as expected, however. 

In order to collapse the annotation, the user can click on the 'Show Highlights' icon and then click on the annotation (and it will become invisible). See this video for a short demo of what I'm experiencing: https://mediaspace.wisc.edu/media/Show+collapse+annotation+bugs+in+PB%2BHypothesis/0_dm8qbxbm.

Like issue #380 I think this bug is connected to the show/hide annotations button and window configuration settings used by hypothesis and some changes we may have introduced with our new js functions.

### Steps to Reproduce

1. Visit https://press.rebus.community/makingopentextbookswithstudents/chapter/open-pedagogy/
2. Try to expand an annotation by clicking on it. Fail because the annotations are invisible.
3. Click view annotations icon (which appears to be toggled on by visibility state)
4. Expand an annotation by clicking on it. It works! 
5. Now click the annotation to collapse it. It doesn't collapse :-(
6. Now click the view annotations icon again to toggle off. Annotations disappear.
7. Now click an annotation (even though invisible)--the toolbar collapses. 

**Expected behavior:** 
1. Annotation visibility should match the visibility state icon (eye open = visible, eye closed = invisible)
2. Clicking an annotation should change the pane's status (if closed upon click, it should open, if open upon click, it should close).

**Comment by gunha** [comment]
Hello!

I did some testing with McLuhan 2.6.1 and it looks like everything is working as expected except for one thing: when I click on the same highlighter annotation, the annotation pane does close (as described in Steel's second expected behavior above)

Here's a gif for reference: 
![pressbooks testing](https://user-images.githubusercontent.com/10037660/49961021-34ad5a80-fed7-11e8-85b5-99cf1629f31a.gif)

**Comment by SteelWagstaff** [comment]
Hey Andrew--I miswrote the expected/desired behavior in the initial ticket. The annotation pane should only close when a user clicks _outside_ of an annotation. My colleague @mcgratay helped point out my error, and I edited the desired functionality in the initial report. Hope that makes sense?

**Comment by gunha** [comment]
Ahh -- Ok that's good to know. I thought clicking on the same annotation would close the pane in the past, so I kind of assumed that's what the desired functionality was for this fix. 

Thanks to both you and @greatislander for working to quickly to address this!

**Comment by SteelWagstaff** [comment]
Yeah--I thought so too, but I think we were both mistaken in our recollection. I tested and tried on lots of other sites that use Hypothesis outside of the Pressbooks world, and none of them close the pane when an open annotation is clicked--rather, they all close the annotation pane only when a user clicks somewhere on the page that isn't annotated.
