### ISSUE TITLE
Latest release aetna@1.0.0-alpha.21 causes GitHub Updater to fail on update

### ISSUE THREAD

**Issue by figureone** [pressbooks/pressbooks-book#427]
Aloha, `aetna@1.0.0-alpha.21` release published yesterday is breaking any attempted updates to McLuhan, because GitHub Updater tries to fetch that as the latest release when updating to `2.6.1`.
https://github.com/pressbooks/pressbooks-book/releases

Unpublishing it should fix the issue, but if needed I can provide more details on why GitHub Updater fails. This is the error caused during update:
```
[Wed Dec 19 10:38:10.511109 2018] [:error] [pid 17595] [client 172.17.5.134:58048] PHP Warning:  preg_match() expects parameter 2 to be string, object given in /var/www/html/wp-admin/includes/class-wp-upgrader.php on line 258, referer: https://example.edu/wp-admin/network/update-core.php?action=do-theme-upgrade
```

**Comment by greatislander** [comment]
Thanks for reporting this! It was just supposed to be a tag, not a release. I've unpublished. Let me know if it works for you now.

**Comment by figureone** [comment]
Yep, works now, thanks for the quick turnaround!

It did, however, require a refresh of the GitHub Updater cache.
<img width="571" alt="screen shot 2018-12-19 at 11 47 56 am" src="https://user-images.githubusercontent.com/125274/50250079-f525b900-0383-11e9-9fb7-90c578155620.png">

FYI, the specific reason it failed was because that alpha release did not have any `assets` in the API response. Example response:
https://api.github.com/repos/pressbooks/pressbooks-book/releases/14498695

GitHub Updater looks for that array to grab the release's `browser_download_url` to fetch, but since the bad release didn't include the `assets` array, the whole response object was getting passed back to WordPress in place of the download URL, causing the error above.
https://github.com/afragen/github-updater/blob/develop/src/GitHub_Updater/Traits/API_Common.php#L73
