### ISSUE TITLE
Catalog image & cover page background theme option

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks-book#44]
### Description

Add web theme options for `Catalog Image` and `Cover Page Background`. Image will be used:

1. On [Aldine](https://github.com/pressbooks/pressbooks-aldine/issues/20)'s catalog page (296px &times; 323px format).
2. On the book cover page (1920px &times; 960px format).

**Web Theme Options**

_Catalog Image_: This image will appear on your webbook’s cover page and in the network catalog (if applicable). Catalog image should be 2:1 aspect ratio. Recommended minimum dimensions are 1920px &times; 960px, maximum file size is 2MB.

(User can upload or choose from presets. Uploads will be validated for minimum size and aspect ratio.)

_Cover Page Background_: Light / Dark (toggle switch).

**Comment by SteelWagstaff** [comment]
See also https://docs.google.com/document/d/1-YJ4lW8QeYYfBHnjwx90rqnaZWq1VpYwaQlv0kAYUII/edit?usp=sharing (internal PB access only) for very old spec document

**Comment by pb-amy** [comment]
This request has come in numerous times from different clients, and most recently in this client interaction: https://pressbooks.zendesk.com/agent/tickets/5144

**Comment by SteelWagstaff** [comment]
Closing in favor of https://github.com/pressbooks/pressbooks-aldine/issues/342
