### ISSUE TITLE
When validating an epub3 file with http://validator.idpf.org/application/validate I get 'The entity "nbsp" was referenced, but not declared.'

### ISSUE THREAD

**Issue by thomasdumm** [pressbooks/pressbooks-book#447]
### Prerequisites

* [ ] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [McLuhan](http://github.com/pressbooks/pressbooks-book/releases/latest/), and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing the issue while using this book theme?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-book) to see if your bug or enhancement is already listed?

When validating an epub3 file with http://validator.idpf.org/application/validate I get 'The entity "nbsp" was referenced, but not declared.'

#### Book Info

Book ID: 22
Book URL: https://pressbooks.delivros.ch/oeffentlichesrecht/
Book Privacy: Public

#### Browser

Platform: OS X
Browser Name: Firefox
Browser Version: 64.0
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:64.0) Gecko/20100101 Firefox/64.0

#### WordPress Configuration

Network URL: http://pressbooks.delivros.ch/
Network Type: Subdirectory
Version: 5.0.2
Language: en_US
WP_ENV: development
WP_DEBUG: Disabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 5.6.3
Book Theme: McLuhan
Book Theme Version: 2.6.1
Root Theme: Aldine
Root Theme Version: 1.5.0

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

Advanced WPLink: 1.1.0
Enable Media Replace: 3.2.7
Import users from CSV with meta: 1.12.1
Pressbooks: 5.6.3
Pressbooks LTI Provider: 1.1.2
Re-send Welcome Email: 0.4.2
Really Simple SSL: 3.1.3
Really Simple SSL pro multisite: 2.0.21
Simple History: 2.29.1
WP Mail SMTP: 1.4.1

#### Book Active Plugins

Advanced WPLink: 1.1.0
Enable Media Replace: 3.2.7
Import users from CSV with meta: 1.12.1
Pressbooks: 5.6.3
Pressbooks LTI Provider: 1.1.2
Re-send Welcome Email: 0.4.2
Really Simple SSL: 3.1.3
Really Simple SSL pro multisite: 2.0.21
Simple History: 2.29.1
WP Mail SMTP: 1.4.1

#### Inactive Plugins

Co-Authors Plus: 3.3.1
H5P: 1.11.3
Hypothesis: 0.5.0
PublishPress: 1.18.0
PublishPress Multiple Authors: 2.1.3
WP QuickLaTeX: 3.8.6

#### Server Configuration

PHP Version: 7.2.9-1+ubuntu16.04.1+deb.sury.org+1
MySQL Version: 5.7.24
Webserver Info: Apache/2.4.18 (Ubuntu)

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 256M
Upload Max Size: 128M
Post Max Size: 128M
Upload Max Filesize: 128M
Time Limit: 90
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: N/A

#### PHP Extensions

OPcache: Zend
XDebug: Disabled
cURL: Supported
cURL Version: 7.47.0
imagick: Not Installed
xsl: Installed

**Comment by greatislander** [comment]
https://github.com/geek1011/kepubify/issues/26
