### ISSUE TITLE
MOBI: textboxes which break between pages can cause display issues

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks-book#474]
### Description

Subsequent headers within a textbox break strangely across pages in MOBI.

![870648148812979 qpu1we3sbxfmsuiyoa3g_height640](https://user-images.githubusercontent.com/605361/51698133-d6988a80-1fdf-11e9-9735-6e03a263a386.png)

### Steps to Reproduce

**Expected behavior:** Textbox background is consistently displayed behind all elements.

**Actual behavior:** The last element before the page break displays "outside" the textbox.

**Comment by mcgratay** [comment]
Cannot reproduce. 

Tested: Andreesen, Malala
