### ISSUE TITLE
PDF: adding footnote from within element other than paragraph leads to discrepancies in footnote display

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks-book#480]
### Description

Adding a footnote from within an element other than a paragraph causes the footnote to inherit that element's styles in PDF. This is a known limitation of the paged media model's footnote display technique.

### Steps to Reproduce

1. Add a footnote in a blockquote.

**Expected behavior:** The footnote displays normally.

**Actual behavior:** The footnote inherits blockquote styles.

**Comment by mcgratay** [comment]
Cannot reproduce.
