### ISSUE TITLE
Disable scroll animation 

### ISSUE THREAD

**Issue by mcgratay** [pressbooks/pressbooks-book#488]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [McLuhan](http://github.com/pressbooks/pressbooks-book/releases/latest/), and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing the issue while using this book theme?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-book) to see if your bug or enhancement is already listed?

### Description

When links to anchors are clicked in a webbook, the page scrolls down to the anchor location after the user lands on the top of the new page. This behavior has been reintroduced after a period in which clicking on a link brought the user directly to the anchor without any scroll animation. 

Some users may prefer to disable the scroll animation and link readers directly to anchors. 

### Steps to Reproduce

1. Add an anchor to the middle of a chapter in Pressbooks using the anchor tool on the Visual Editor toolbar
2. Add a link from somewhere else in the book to this anchor
3. Save your changes, and open the webbook to the chapter that contains the link 
4. Click the link to see the scroll animation that leads to the anchor 

**Expected behavior:** Users can choose whether internal links in their book scroll to anchors or not 

**Actual behavior:** Users have control over whether a page scrolls to an anchor or doesn't.

**Comment by greatislander** [comment]
Maybe better to just remove the animation altogether…
