### ISSUE TITLE
Unable to upload image for Catalog Profile

### ISSUE THREAD

**Issue by emasters** [pressbooks/pressbooks-book#51]
### Prerequisites

_Check the boxes below by changing them from `[ ]` to `[x]`._

* [x] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [Pressbooks Book](http://github.com/pressbooks/pressbooks-book/releases/latest/), and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [ ] Are you experiencing the issue while using this book theme?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-book) to see if your bug or enhancement is already listed?

### Description

When using the My Catalog Profile feature I am unable to upload a logo or image. I can browse my local file system for an image and the filename shows next to the browse button but there is no upload button. Hitting save changes generates the following error that appears on our dev platform: `Fatal error: Call to undefined function Pressbooks\wp_handle_upload() in /vol/data/pressbooks.calidev.org/wp-content/plugins/pressbooks/inc/class-catalog.php on line 731`

This behavior happens on both our development and production platforms for all users.

### Steps to Reproduce

1. Starting on **My Catalog** page, click on **Catalog Profile** link under **Catalog sorting** heading
2. On **My Catalog Profile** page under **Logo or Image** click **Browse** and locate an image
3. Click **Open** on **File Upload** window
4. Click **Save Changes**, only option available on **My Catalog Profile** page

**Expected behavior:** I expected to be able to add some image that would replace the default image on my personal catalog page.

**Actual behavior:** Image did not load and an error was generated.

#### Root Blog Info

Root Blog ID: 1
Root Blog URL: http://pressbooks.calidev.org/

#### Browser

Platform: Windows
Browser Name: Firefox
Browser Version: 58.0
User Agent String: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0

#### WordPress Configuration

Network URL: http://pressbooks.calidev.org/
Network Type: Subdirectory
Version: 4.8.3
Language: en_US
WP_ENV: Not set
WP_DEBUG: Enabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 4.3.5
Root Theme: Pressbooks Publisher
Root Theme Version: 3.0.1

#### Pressbooks Dependencies

Epubcheck: Not Installed
Kindlegen: Not Installed
xmllint: Not Installed
PrinceXML: Not Installed
Saxon-HE: Not Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

Pressbooks: 4.3.5
Pressbooks Textbook: 3.1.6

#### Inactive Plugins

Akismet Anti-Spam: 4.0.1
Default Theme: 1.0.4
Hello Dolly: 1.6
WPMU DEV Dashboard: 4.4

#### Server Configuration

PHP Version: 5.6.23-1+deprecated+dontuse+deb.sury.org~trusty+1
MySQL Version: 5.5.54
Webserver Info: Apache/2.4.16 (Ubuntu) OpenSSL/1.0.1f

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 256M
Upload Max Size: 256M
Post Max Size: 256M
Upload Max Filesize: 256M
Time Limit: 180
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: On (1)

#### PHP Extensions

OPcache: Zend
XDebug: Disabled
cURL: Supported
cURL Version: 7.35.0
imagick: Not Installed
xsl: Installed

**Comment by greatislander** [comment]
Hi @emasters, this is actually a bug with Pressbooks, not the book theme. I've submitted a pull request to fix it there.

**Comment by emasters** [comment]
D'oh! I had both issue queues open at some point yesterday and dropped this in the wrong one. Sorry about that. Thanks @greatislander for catching and fixing this. 
I'll keep better track of where I am next time.
