### ISSUE TITLE
(MOBI) Content wrapped in a column does not display in columns but other column styles remain

### ISSUE THREAD

**Issue by dannylonglegs** [pressbooks/pressbooks-book#520]
### Description
The text at the top of the image displays in columns in other formats, but not in MOBI. Expected behavior would be that if columns aren't compatible with the format, the text would revert to normal body text. Instead, it maintains the column text font size and displays smaller than body text
![image](https://user-images.githubusercontent.com/21149722/53433839-37dac180-39c3-11e9-9a89-c280d79904aa.png)

**Expected behavior:** 
Expected behavior would be that if columns aren't compatible with the format, the text would revert to normal body text.
**Actual behavior:** 
 It maintains the column text font size and displays smaller than body text

**Comment by SteelWagstaff** [comment]
Wont fix
