### ISSUE TITLE
WEB: Blockquotes with <blockquote> tags do not display in webbook without there also being <div> tags

### ISSUE THREAD

**Issue by dannylonglegs** [pressbooks/pressbooks-book#521]
### Description

Blockquotes with <blockquote> tags do not display in webbook without there also being <div> tags
![image](https://user-images.githubusercontent.com/21149722/53436305-e9c8bc80-39c8-11e9-8dcd-34a88b9db84b.png)

### Steps to Reproduce

1. Create blockquote in book
2. Navigate to blockquote to see issue

**Expected behavior:** Blockquote styles should be consistent across all formats

**Actual behavior:** Blockquote styles on web do no display properly

**Comment by mcgratay** [comment]
Cannot reproduce. Tested: Malala, Adunis, Andreesen, McLuhan.
