### ISSUE TITLE
PDF Export: Parse error in value of property 'color' at '('

### ISSUE THREAD

**Issue by connerbw** [pressbooks/pressbooks-book#527]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [McLuhan](http://github.com/pressbooks/pressbooks-book/releases/latest/), and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing the issue while using this book theme?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-book) to see if your bug or enhancement is already listed?

### Description

> Wed Mar 20 10:27:01 2019: [...]prince-1553092017.css:452: warning: parse error in value of property 'color' at '('

```
dl dt {
  display: block;
  margin: 0 0 0 0;
  font-style: normal;
  font-weight: bold;
  color: (epub: initial, prince: initial, web: #373d3f); }
```

### Steps to Reproduce

1. Turn on "Yes. Email me validation error logs on export."
2. Export PDF

**Expected behavior:** 

SCSS maps have been parsed, uses `prince` key, converts to valid CSS

**Actual behavior:** 

SCSS maps not working for this particular CSS element

**Comment by thomasdumm** [comment]
I also came accross this error but only checked github after digging why this happens. So in case this helps:
in the _colors.scss partial the color is format dependet:

```
$color-1: (
  epub: initial,
  prince: initial,
  web: #373d3f
) !default;
$color-3: $color-1 
```
in the _lists.scss partial the if-map-get is missing the  color: $dt-color; in this part:

```
%dt {
  display: block;
  margin:
    if-map-get($dt-margin-top, $type)
    if-map-get($dt-margin-right, $type)
    if-map-get($dt-margin-bottom, $type)
    if-map-get($dt-margin-left, $type);
  font-style: $dt-font-style;
  font-weight: $dt-font-weight;
  color: $dt-color;
}
```
