### ISSUE TITLE
PhET simulations not loading when inside of a collapsible webbook section 

### ISSUE THREAD

**Issue by mcgratay** [pressbooks/pressbooks-book#541]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [McLuhan](http://github.com/pressbooks/pressbooks-book/releases/latest/), and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing the issue while using this book theme?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-book) to see if your bug or enhancement is already listed?

### Description

PhET simulations that are under an H1 with the Collapsible Subsections setting enabled will not load when the section is opened in a webbook. 

**NOTE:** PhET activities do load after the page has been refreshed. 

Example: https://phetcollapse.textopress.com/

### Steps to Reproduce

1. Create a book or access an existing one on Pressbooks
2. Add a chapter, and insert a PhET activity (ex: https://phet.colorado.edu/sims/html/wave-interference/latest/wave-interference_en.html) via the visual editor
3. Create a heading and tag it with paragraph style H1, then add another PhET simulation underneath the heading and save the chapter
4. Navigate to **Appearance > Theme Options > Web Options** and enable the Collapse Sections setting, then save changes 
5. View the webbook and open the collapsed section to see if the activities load 

**Expected behavior:** PhET simulations load when a collapsed section is first expanded

**Actual behavior:** PhET simulations will not load on first visit if they are placed inside a collapsed section

**Comment by SteelWagstaff** [comment]
May be related to what was causing a similar issue with H5P acitivities: https://github.com/pressbooks/pressbooks-book/issues/492?

**Comment by connerbw** [comment]
The bug is in PhET.

If you view the JavaScript console in the example book you'll see JavaScript prints two errors (one for each hidden PhET simulation). When JavaScript crashes like that, it stops running. 

The code (over at https://phet.colorado.edu/sims/html/wave-interference/latest/wave-interference_en.html) is trying to run on an invisble/hidden/{non-extstant until expanded} property and it fails. 

We should report this issue to PhET.


![image](https://user-images.githubusercontent.com/812192/58355285-d8654400-7e41-11e9-9332-3fde451b3371.png)

**Comment by SteelWagstaff** [comment]
Reported at https://github.com/phetsims/tasks/issues/1002

**Comment by connerbw** [comment]
Hack doesn't work with two sections, steps to reproduce:

1. Go to: https://languagetest.textopress.com/chapter/phet/
1. Open 2nd collapsed section 1st
1. Open 1st collapsed section 2nd

Expected: PHeT iframe reloaded
Actual: No change

**Comment by mcgratay** [comment]
Resolved.
