### ISSUE TITLE
H5P activity Agamotto does not load if inside a collapsible section in a webbook

### ISSUE THREAD

**Issue by mcgratay** [pressbooks/pressbooks-book#550]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [McLuhan](http://github.com/pressbooks/pressbooks-book/releases/latest/), and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing the issue while using this book theme?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-book) to see if your bug or enhancement is already listed?

### Description

A webbook will only display the first small section of the H5P activity Agamotto if the activity has been placed inside of a collapsible section. The Agamotto activity will load and display fine outside of a collapsible section. It also loads completely if the collapsible section is collapsed and then expanded again. The problem occurs when the section is first expanded for each visit or refresh of the webpage. 

Example: https://collapsedsectionerrors.textopress.com/chapter/agamotto-h5p/ 

![Screen Shot 2019-05-24 at 4 39 48 PM](https://user-images.githubusercontent.com/39064028/58355518-9688cd80-7e42-11e9-9b79-3aec038a5240.png)

### Steps to Reproduce

1. Create a new book or access an existing book 
2. Active the H5P plugin
3. Create an Agomotto (Image Blender) H5P activity 
4. Add the H5P activity to a chapter 
5. Add a heading tagged with Heading Style 1 before the activity and save your chapter 
6. Go to **Appearance > Theme Options > Web Options** and enable the collased sections setting 
7. View the chapter and open the collapsed section 

**Expected behavior:** H5P activities load completely when a collapsed section is expanded

**Actual behavior:** Collapsed sections prevent some activities from successfully dispaying

**Comment by dannylonglegs** [comment]
https://github.com/otacke/h5p-agamotto/issues/39

**Comment by connerbw** [comment]
Plugin still not updated. I left a comment:

https://github.com/otacke/h5p-agamotto/commit/af4dceb0f1ffcad1d80bc4b226d4c5a5de30d8ec#commitcomment-34201564
