### ISSUE TITLE
Division sign displaying incorrectly in McLuhan theme

### ISSUE THREAD

**Issue by josieg** [pressbooks/pressbooks-book#562]
### Prerequisites

* [ ] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [ ] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [McLuhan](http://github.com/pressbooks/pressbooks-book/releases/latest/), and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)? - **No, still on PB 5.6.3**
* [x] Are you experiencing the issue while using this book theme?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-book) to see if your bug or enhancement is already listed?

### Description

When the McLuhan theme is enabled, the division sign is displaying as two vertical dots in the webbook and digital PDF (these were the only exports I checked). The division sign displays as expected (÷) in both the Open Textbooks theme and Clarke.

My guess is that the issue is related to the McLuhan theme `<p>` font. The division sign displays correctly when it is set at any heading level in McLuhan.

### Steps to Reproduce

1. Enable the McLuhan theme in a book.
2. Open a chapter and insert a division sign using the special Character button from the toolbar in the visual editor. (Second row)
3. The division sign is inserted as two dots.

**Expected behavior:** 
I expect the division sign to display properly (i.e., ÷)

**Actual behavior:** 
The division sign appears like a colon (i.e., :)
![division](https://user-images.githubusercontent.com/23706762/59047259-62e17680-8838-11e9-8b1d-30c50308e3c3.jpg)

#### Book Info

Book ID: 621
Book URL: https://pressbooks.bccampus.ca/basickitchenaccessibility/
Book Privacy: Public

#### Browser

Platform: Windows
Browser Name: Firefox
Browser Version: 67.0
User Agent String: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0

#### WordPress Configuration

Network URL: http://pressbooks.bccampus.ca/
Network Type: Subdirectory
Version: 5.0.2
Language: en_US
WP_ENV: Not set
WP_DEBUG: Enabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 5.6.3
Book Theme: McLuhan
Book Theme Version: 2.6.1
Root Theme: Aldine
Root Theme Version: 1.5.0

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

bcc new user notify: 0.0.1
BC Post-Secondary Validator: 1.0.2
CC Export for Pressbooks: 1.0.0
f5 Force SSL: 1.0.0
iThemes Security: 7.2.0
Openstax Import for Pressbooks: 1.3.2
Pressbooks: 5.6.3
Pressbooks Stats: 1.6.2
Textbooks for Pressbooks: 4.2.3
WP-Piwik: 1.0.19

#### Book Active Plugins

bcc new user notify: 0.0.1
BC Post-Secondary Validator: 1.0.2
CC Export for Pressbooks: 1.0.0
f5 Force SSL: 1.0.0
iThemes Security: 7.2.0
Openstax Import for Pressbooks: 1.3.2
Pressbooks: 5.6.3
Pressbooks Stats: 1.6.2
Textbooks for Pressbooks: 4.2.3
WP-Piwik: 1.0.19
WP QuickLaTeX: 3.8.5

#### Inactive Plugins

Akismet Anti-Spam: 4.1
Candela Citation: 0.2.2
H5P: 1.11.3
Hypothesis: 0.5.0
mPDF for Pressbooks: 3.2.4

#### Server Configuration

PHP Version: 7.1.29
MySQL Version: 5.5.5
Webserver Info: Apache

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 512M
Upload Max Size: 500M
Post Max Size: 500M
Upload Max Filesize: 500M
Time Limit: 300
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: N/A

#### PHP Extensions

OPcache: Disabled
XDebug: Disabled
cURL: Supported
cURL Version: 7.19.7
imagick: Installed
xsl: Installed

**Comment by SteelWagstaff** [comment]
The issue here is that the ['obelus' character](https://en.wikipedia.org/wiki/Obelus) is missing from the set of glyphs included in the Lora typeface: https://fonts.google.com/specimen/Lora. I've contacted Google Fonts about the missing character, but don't expect a quick or satisfactory answer.

**Comment by SteelWagstaff** [comment]
@josieg there's a newer version of Lora that does include the division sign. I've opened a PR to add the typeface to pressbooks-book that should result in this character displaying properly in exports (see example from my local environment):
![Screenshot from 2021-04-03 16-29-07](https://user-images.githubusercontent.com/13485451/113494057-c91d9b80-9499-11eb-8486-ffa84afafbd0.png)

 Will let you know when it's released and ready for use by open source networks.

**Comment by SteelWagstaff** [comment]
Tested and working as expected on integrations network. Ready for release.
