### ISSUE TITLE
Images cut off of page in MOBI exports

### ISSUE THREAD

**Issue by mcgratay** [pressbooks/pressbooks-book#572]
### Description

Images in a book can move off the page to the right in MOBI exports and cut off. This includes captions. The issue is not consistent and does not seem to be affected by image size, image alignment, or book theme. 

The user noticed the problem in both Kindle Previewer and in the Kindle app version 1.17.0. The alignment of these images was not affected in EPUB files or on PDF. 

View book: https://pendletonsketches.pressbooks.com

### Steps to Reproduce

1. Create a book in Pressbooks
2. Add images
3. Export to MOBI 
4. View in Kindle Previewer and the Kindle app 

**Expected behavior:** All images align according to how they're set using image tools. 

**Actual behavior:** Images in MOBI can sometimes be cut off of the page. 

![Screen Shot 2019-06-19 at 4 23 18 PM](https://user-images.githubusercontent.com/39064028/59797783-8f70a600-92ae-11e9-9dcf-61ab5963d94e.png)
![Screen Shot 2019-06-19 at 4 23 30 PM](https://user-images.githubusercontent.com/39064028/59797792-95668700-92ae-11e9-8638-3ccde74db73d.png)

**Comment by SteelWagstaff** [comment]
Wont fix
