### ISSUE TITLE
Create full grid + full grid landscape table options

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks-book#573]

**Comment by connerbw** [comment]
Deployed to Textopress for testing.

Note: Because the version number of pressbooks-book doesn't change until we officially release something, we must manually trigger SCSS compile for this to work. This can be done by making a Theme Options change and saving it.

**Comment by mcgratay** [comment]
Resolved. Believe we should revisit naming options/UI at a later date.
