### ISSUE TITLE
URLS automatically appear hyperlinked when placed inside of footnotes

### ISSUE THREAD

**Issue by mcgratay** [pressbooks/pressbooks-book#578]
### Description

URLs that are placed within a footnote shortcode appear in the footnotes as live hyperlinks and cannot have their links broken. There is not HTML in the text editor view that appears to cause the hyperlinking, and therefore no way to break the link. 
![Screen Shot 2019-07-04 at 4 30 54 PM](https://user-images.githubusercontent.com/39064028/60686847-1dd15400-9e79-11e9-88ee-c72fccfd2a53.png)
![Screen Shot 2019-07-04 at 4 31 16 PM](https://user-images.githubusercontent.com/39064028/60686855-26c22580-9e79-11e9-831f-36fb8a972727.png)

Example: https://linkimportword.textopress.com/

### Steps to Reproduce

1. Create a chapter 
2. Add a footnote with a plain text URL inside of it 
3. Save the chapter and view  

**Expected behavior:** Only URLs which have had links activated using the visual editor toolbar's link tool should appear as active in the webbook and exports. 

**Actual behavior:** URLs inside of footnotes will display as active, and hyperlinks cannot be removed.

**Comment by connerbw** [comment]
Done on purpose in 2015, approved by @hughmcguire 

+ https://github.com/pressbooks/pressbooks/pull/90
+ https://groups.google.com/forum/#!topic/pressbooks/iORWe_d_MwQ

**Comment by SteelWagstaff** [comment]
Can be fixed by removing make_clickable() from https://github.com/pressbooks/pressbooks/blob/faf341a8050294dcb1dddf31cab1886d01634005/inc/shortcodes/footnotes/class-footnotes.php#L147

**Comment by SteelWagstaff** [comment]
Fix works for webbooks and ebook exports. In digital PDFs, the unlinked content isn't visually indicated as a link, but it can still be clicked and opened by the user. This is a preexisting 'feature,' however, and isn't limited to footnotes alone. Will close this issue and file separate bug report for that.
