### ISSUE TITLE
Details element needs polyfill for Edge/IE

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks-book#584]
### Description
The HTML `<details>` element is supported by over 92% of browsers used globally, but needs polyfills to function properly in IE and Edge (see https://caniuse.com/#search=details). Several Pressbooks users have been using this element to make show/hide components for their books. We'd like to add support for a simply polyfill so that the details element displays as intended in Edge/IE. 

Potential javascript solutions [here](https://gist.github.com/remy/370590), [here](https://github.com/rstacruz/details-polyfill), and [here](https://github.com/mathiasbynens/jquery-details). See also the 'resources' section [here](https://caniuse.com/#search=details).

**Comment by connerbw** [comment]
Used this polyfill:

 + https://www.npmjs.com/package/details-element-polyfill

For it to work, the tag must be [written correctly](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details):

This will work:

```html
<p>Hey There!</p>
<details>
    <summary>This is my summary</summary>
    This is the text I am trying to hide.
</details>
<p>Peace</p>
```

This will not work:

```html
<p>Hey There!</p>
<details>
    This is the text I am trying to hide.
</details>
<p>Peace</p>
```

Looks like this in Edge:

![Edge-Screenshot](https://user-images.githubusercontent.com/812192/64038734-d8529f80-cb26-11e9-8ba5-f35a11c1d131.png)

**Comment by SteelWagstaff** [comment]
Tested in Edge and IE 11. Details elements worked in both (though the page looked awful in IE 11). When H5P elements are included, they are not visible until the page is inspected, but this is not specific to these browsers. See https://github.com/pressbooks/pressbooks-book/issues/492#issuecomment-461156103
