### ISSUE TITLE
Videos not responsive to window sizing, cut off on mobile screen

### ISSUE THREAD

**Issue by mcgratay** [pressbooks/pressbooks-book#592]
### Description

Videos in webbooks entered via most methods will not resize responsively to a user's screen when they view a webbook. Here is a list of example video adding methods that result in this: 

- copy-pasting oEmbed-compatible video links directly into the visual editor
- [embed] shortcode
- [media] shortcode 
- H5P video interactive element 

The only way to get a video to resize was to embed it via iframe with the height specified and the width set to 100%. Attempts to set the width to 100% via the embed shortcode resulted in the video being set to 100 pixels instead. Any video inserted using default methods (described above) results in a distorted nav menu on mobile screens. 

![Screen Shot 2019-08-30 at 4 41 51 PM](https://user-images.githubusercontent.com/39064028/64050120-13fc6200-cb45-11e9-8c72-6af559ea32de.png)

Example: https://videoresizingissues.textopress.com/

### Steps to Reproduce

1. Copy/paste a YouTube URL into a chapter
2. Save and view chapter in the webbook format on a mobile-sized screen 
3. View video to see if it has resized to the mobile screen width 

**Expected behavior:** Videos do not exceed 100% of screen size and always resize according to the size of a window. Ideally, video height is proportional to video width as a video resizes.  

**Actual behavior:** Only videos embedded via iframe can be mobile responsive.

**Comment by SteelWagstaff** [comment]
Interesting jquery_based possible implementation described in this CSS Tricks article: https://hyp.is/rvDRFtSaEemgaxuryE4bIg/css-tricks.com/NetMag/FluidWidthVideo/Article-FluidWidthVideo.php

**Comment by mcgratay** [comment]
Good to go. All default video embed methods now result in automatically responsive videos - as long as the user doesn't set a fixed height the video should remain proportional.
