### ISSUE TITLE
All chapters are nested underneath the last front matter post in the PDF bookmarks when a book has only one Part

### ISSUE THREAD

**Issue by mcgratay** [pressbooks/pressbooks-book#598]
### Description

If a book only contains one Part, then all chapters will nest under the last front matter post in the PDF bookmarks. This incorrectly makes it look like the chapters are all part of, for example, the introduction. 

Because "parts" become redundant in a book that only contains one part, chapters should move up one level in hierarchy when this occurs and be equal to front matter and back matter posts. 

![Screen Shot 2019-09-04 at 12 28 01 PM](https://user-images.githubusercontent.com/39064028/64273649-bd5da200-cf0f-11e9-97f7-35d32dbe1193.png)

Example: https://philosophyrebusaccessiblemarkup.textopress.com/

### Steps to Reproduce

1. Create a new book 
2. Add a few chapters to the existing Part (note: do not add another Part) 
3. Export to PDF and view bookmarks

**Expected behavior:**  In a book without parts, chapters are not nested under any other element

**Actual behavior:** Chapters in books with less than 2 parts are nested under the last front matter post

**Comment by SteelWagstaff** [comment]
@tw77 I believe this issue is now fixed in latest release of Pressbooks. Will you confirm?

**Comment by tw77** [comment]
Yes, this issue with the PDF bookmarks has been fixed. Chapters are no longer nested under the last front matter post ("Introduction to the Book"):

<img width="211" alt="Screen Shot 2022-01-06 at 1 58 10 PM" src="https://user-images.githubusercontent.com/44182629/148458023-35b7bffc-cd3a-40be-acdb-9f54a65e3b15.png">


.
