### ISSUE TITLE
MOBI validation errors affecting Andreesen and Tufts themes 

### ISSUE THREAD

**Issue by mcgratay** [pressbooks/pressbooks-book#606]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [McLuhan](http://github.com/pressbooks/pressbooks-book/releases/latest/), and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing the issue while using this book theme?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-book) to see if your bug or enhancement is already listed?

### Description

The Andreesen and Tufts themes are both being flagged for a specific set of errors that's preventing validation: 

Error(core):E1003: Unknown error in class String.
Error(parsing):E3013: More number of characters are hidden using display:none than allowed limit. Limit: 10000  

However, the error affects the books differently. 

**Andreesen**
- For the Parsing Error, it flags one chapter each time: chapter 6. If the first chapter 6 is removed from the book, it flags the second chapter 6. If you remove both of those chapters, the book exports fine
- Attempted to remove one entire chapter and systematically narrow down what the issue was with the other one. Stripped out all: videos, links, images, stylistic elements. If you remove _all_ text and content from the chapter, it exports fine. But even with no HTML tags in the chapter, the export would still get flagged
- Exports do appear, but are flagged as having errors
- Error _does not affect any other themes_ when testing this book (incl Tufts) 

**Tufts**
- Error is the same as above when exported from the Tufts network. That error does not appear when the same book is exported from Textopress
- On the Textopress network, the MOBI files will export, with errors; on the Tufts network the same book will not export at all 
- Error _does_ affect this book on other themes, but only on the Tufts network

Textopress (Andreesen) https://ebookerrorcomm543.textopress.com
Textopress (Tufts) https://mobitesttufts.textopress.com
Tufts (Tufts) https://tuftsmedicine.pressbooks.pub/sfmsection2/

### Steps to Reproduce

1. View books at above links
2. Select appropriate theme from **Appearance**
3. Export to MOBI 

**Expected behavior:** No errors to prevent validation in exported MOBI files

**Actual behavior:** Errors concerning hidden content are preventing some books from exporting to MOBI

**Comment by connerbw** [comment]
> That error does not appear when the same book is exported from Textopress

I can reproduce Tufts error on Textopress by enabling two-level table of contents in global options.

**Comment by connerbw** [comment]
![image](https://user-images.githubusercontent.com/812192/67526377-a40ce280-f682-11e9-9008-a4bc485eeff2.png)

**Comment by mcgratay** [comment]
Seems resolved. Based on comments on Slack, I also checked out Dillard, which has a theme option to enable or disable a chapter decoration. No errors.
