### ISSUE TITLE
Remove/suppress Media Attachment pages

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks-book#611]
By default, WordPress creates a separate media attachment page each time a file is uploaded to the media library. In Pressbooks this page has its own automatically generated URL and contains nothing except the media content. One problem user have experienced is that some media files used in open textbooks are openly licensed images where usage requires proper attribution. Images may receive attribution in the webbook, but this attribution does not currently display on the standalone attribution page. This can be a problem. 

We should either add attribution information to the attribution page or remove/suppress these pages for users. If we choose the latter option, we may also wish to exclude these attachment pages from our sitemap and add noindex & nofollow tags to the meta for all attachment single pages.

**Comment by connerbw** [comment]
Fix redirects attachment URLs to parent post URL (or home page if no parent is found)

**Comment by mcgratay** [comment]
The attachment "Edit Media" page can still be navigated to from a handful of locations, and each "Edit Media" page includes links to the attachment page that now direct somewhere unexpected. 

Solution 1: 
Change the Edit Media page to remove links to the webbook attachment page. One is "View Attachment Page" in the top nav, and the other is the permalink below the image title 
![Screen Shot 2019-10-25 at 2 12 46 PM](https://user-images.githubusercontent.com/39064028/67594105-9ebaa100-f731-11e9-88fa-8ce275ce7501.png)
Alternatively, the text of those two links could be changed to reflect their actual link destination: "View Chapter" and "http://mctesterson.textopress.com/chapter/image-attachment-test/" 

Solution 2: 
Remove all links that let users navigate to the Edit Media page. This includes: 
- The "Edit More Details" button on the Attachment Details page (navigate to **Media Library** in block form and then click on any image) 
![Screen Shot 2019-10-25 at 2 15 54 PM](https://user-images.githubusercontent.com/39064028/67594330-15f03500-f732-11e9-91fa-e9d8be6ed0e6.png)
- The "Edit" button on the Media Library page when in list form
![Screen Shot 2019-10-25 at 2 18 45 PM](https://user-images.githubusercontent.com/39064028/67594471-68c9ec80-f732-11e9-8ab1-df9bc32b6a04.png)

In either case, it's probably also a good idea to remove or change the "View" button on the Media Library list (see above image).

**Comment by connerbw** [comment]
Thank you @mcgratay for your thoughtful, thorough testing. 

The "view" strings are not filterable in a few cases. Suppressing this info in the admin makes a small unplanned patch much larger. It would include difficult to maintain CSS hacks to hide things from a logged in user.

For now, I have changed the code to _do nothing_ if a user can `upload_files`. This solves for anonymous users, bots, subscribers, and the least privileged contributors. More info on `upload_files` permission can be found here: 

https://wordpress.org/support/article/roles-and-capabilities/

**Comment by connerbw** [comment]
PS: It is possible to plug the function(s) into the media attachments page. It would require work we did not intend to do during the sprint (hashtag: Unplanned). We went with _"or remove/suppress these pages for users"_ in the hopes that it would be quick and simple. A message to future developers who would like to explore _"either add attribution information to the attribution page"_, the code you want to plug into the media attachment page is here:

https://github.com/pressbooks/pressbooks/blob/1bf79cf36beaf950e8e50aeee7a4803b64d85388/inc/shortcodes/attributions/class-attachments.php#L75

https://github.com/pressbooks/pressbooks/blob/1bf79cf36beaf950e8e50aeee7a4803b64d85388/inc/shortcodes/attributions/class-attachments.php#L122

https://github.com/pressbooks/pressbooks/blob/1bf79cf36beaf950e8e50aeee7a4803b64d85388/inc/shortcodes/attributions/class-attachments.php#L185
