### ISSUE TITLE
Add clear:both to elements that typically appear at bottom of page (media attributions & footnotes)

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks-book#626]
Right now, if a chapter ends with a floating image, footnotes & media attributions will wrap around it (web, McLuhan on Textopress). In PDF exports, chapter endnotes float around the image. Example: https://jctestbook.textopress.com/chapter/chapter-2/

**Comment by ricardopressbooks** [comment]
branch **pb-290-footnotes**

**Comment by SteelWagstaff** [comment]
Tested extensively on integrations and local. Fixes issue for footnotes, but not for 'media-attributions' class. 

Two notes: 
1. SCSS has been placed in unexpected location (https://github.com/pressbooks/pressbooks-book/blob/dev/assets/src/styles/layouts/_page.scss) instead of https://github.com/pressbooks/pressbooks-book/blob/ca679cd5e3fe74a054886297db9ff3034f5587f2/assets/styles/components/_specials.scss. 2. I'm worried about choice of `display: inline-block` rather than `clear: both` as well, since .footnote already had a display value set (https://github.com/pressbooks/pressbooks-book/blob/741a2af8663e3aa80b7b80f0e3eb6ff335d296e4/packages/buckram/assets/styles/components/specials/_footnotes.scss#L27) which may have been important in Prince?

**Comment by SteelWagstaff** [comment]
Just remembered that we already define a '.clear' class in Buckram: https://github.com/pressbooks/buckram/blob/a827e30f7cf73a00fe52a31ec3976ea3a2964a5b/assets/styles/components/specials/_floats.scss#L9-L11. Cleaner solution would be to apply this class to media-attribution and footnote elements upon creation, I think. PR coming up soon.
