### ISSUE TITLE
Add hanging indent for chapter titles which span multiple lines in the webbook ToC

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks-book#627]
Currently, long chapter titles do not feature any indentation at all in the webbook table of contents:
![current_toc](https://user-images.githubusercontent.com/13485451/69480964-ad50b280-0dda-11ea-853f-d9db4da5f4c1.png)

By adding text-indent and padding-left rules to these elements, would could produce an easier to read hanging indent. Using the sample CSS: 
> .toc [class*=""--empty""]>.toc__title {     text-indent: -1.18rem; padding-left: 1.18rem; }"

A reader would see a ToC that looks like the following (for numbered chapters):
![ToC indent](https://user-images.githubusercontent.com/13485451/69480985-e38e3200-0dda-11ea-89c0-cd4f37b4e59c.png)

and the following (for numberless chapters):
![ToC indent numberless](https://user-images.githubusercontent.com/13485451/69480984-e38e3200-0dda-11ea-9932-c8c6bc43138e.png)

This additional CSS could presumably be added here: https://github.com/pressbooks/pressbooks-book/blob/600391fae72c707f4b08a1f2487b150cb9e2217c/assets/src/styles/components/_toc.scss#L78-L80

**Comment by mcgratay** [comment]
For consistency, I'd recommend also adding the same style modification to Part titles: 
![Screen Shot 2020-02-07 at 2 44 38 PM](https://user-images.githubusercontent.com/39064028/74060710-8c9b0080-49b8-11ea-9e57-cb761a134524.png)
![Screen Shot 2020-02-07 at 2 45 05 PM](https://user-images.githubusercontent.com/39064028/74060712-8d339700-49b8-11ea-88e8-ea6e864aa737.png)

Other than that, looks good to go.

**Comment by SteelWagstaff** [comment]
Oooh, good catch. Will add PR addressing this shortly.

**Comment by mcgratay** [comment]
![Screen Shot 2020-02-12 at 2 28 10 PM](https://user-images.githubusercontent.com/39064028/74370005-60aac100-4da4-11ea-9a9d-96fa2657167d.png)

The designer in me doesn't like that the subsequent lines in each of these three cases aligns differently with the first line. This ticket is technically done, though.

**Comment by SteelWagstaff** [comment]
I feel the same way. Totally get your point -- it has to do with numbering & character width (bc we aren't using a monospace font).
