### ISSUE TITLE
Fix "Other Service URL" buy link option

### ISSUE THREAD

**Issue by mcgratay** [pressbooks/pressbooks-book#630]
### Description

Pressbooks allows users to link to print-on-demand and ebookstore services through the Publish page in the Pressbooks book admin interface, which displays on a "BUY THE BOOK" page navigable from the webbook. 

![Screen Shot 2019-11-28 at 1 45 46 PM](https://user-images.githubusercontent.com/39064028/69827424-62bda480-11e5-11ea-9043-a264130d9fc3.png)

By default, Pressbooks supports links for Amazon, O'Reilly, Barnes&Noble, Kobo, and Apple. Links to other stores must be put into the "Other Services URL" section: 

![Screen Shot 2019-11-28 at 1 46 27 PM](https://user-images.githubusercontent.com/39064028/69827440-7b2dbf00-11e5-11ea-9a4a-2b059943dcfa.png)

Which displays the word "Elsewhere" hyperlinked to the webpage as well as displaying the hyperlinked URL. 

![Screen Shot 2019-11-28 at 1 47 57 PM](https://user-images.githubusercontent.com/39064028/69827521-b0d2a800-11e5-11ea-9e90-d8af032db697.png)

There's no way to edit this page, so there's no way for a user to fix the word "Elsewhere" bumping up against the plain text phrase "Purchase here." 

An improvement would be to just remove the word Elsewhere and display only "Purchase here: [link]. 

### Steps to Reproduce

1. Go to **Publish** from the left sidebar menu of your book dashboard
2. Enter a URL in the "Other Service URL" textbox and save changes
3. Go to the webbook and click the "BUY" link 
4. View the page 

**Expected behavior:** The display of the purchase link is intentionally designed and doesn't have typos/errors. 

**Actual behavior:** The buy link for "other services" has two redundant links, one of which bumps up against the rest of the text without spaces.

**Comment by SteelWagstaff** [comment]
Should be able to be fixed quickly at https://github.com/pressbooks/pressbooks-book/blob/ddcb6a3167903e2b6092efda04d72f751acab887/page-buy.php#L50

**Comment by cagp-dev-mtl** [comment]
PR for this fix:

https://github.com/pressbooks/pressbooks-book/pull/666

**Comment by mcgratay** [comment]
looks good 👍
