### ISSUE TITLE
Improve phrasing of media attributions to reflect accepted standard

### ISSUE THREAD

**Issue by mcgratay** [pressbooks/pressbooks-book#631]
### Description
The media attribution statement that appears when a user has enabled the Media Attributions theme option on the Global Option page does not display as readers would expect it to and doesn't follow general conventions for Creative Commons license statements. 

Currently, all media attributions statements read: 

[IMAGE TITLE] by [AUTHOR NAME] © [LICENSE]

Users expect this statement to display as: 

[IMAGE TITLE] © [AUTHOR NAME] is licensed under a [LICENSE] license 

Example: https://attributionsandlicenses.textopress.com/

### Steps to Reproduce

1. Create a new chapter and click **Add Media** to upload an image
2. Once the image is uploaded, fill in the **Attributions** section with the image source URL, author, and license, then insert into chapter. Save changes. 
3. Go to **Appearance > Theme Options > Global Options** and enable the Media Attributions theme options. Save changes. 
4. View webbook version of new chapter, and scroll down to see license statements. 

**Expected behavior:** Media attributions statements match publishing conventions. 

**Actual behavior:** Some parts of the license statement need to be rearranged.

**Comment by SteelWagstaff** [comment]
Attribution statements are created using this function: https://github.com/pressbooks/pressbooks/blob/49ed2a83c71645495c02dddd933b898a7daacb0b/inc/shortcodes/attributions/class-attachments.php#L185-L266

**Comment by cagp-dev-mtl** [comment]
PR for this ticket is ready for review:

https://github.com/pressbooks/pressbooks/pull/1892

**Comment by mcgratay** [comment]
![Screen Shot 2020-02-12 at 2 14 47 PM](https://user-images.githubusercontent.com/39064028/74368624-07da2900-4da2-11ea-838e-03ede7d7ca0c.png)

looks good, folks
