### ISSUE TITLE
Fix 'aria-expanded' javascript bug for ToC

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks-book#647]
A recent PR added some javascript functionality to improve the accessibility of the download files tool on a book's homepage. Unfortunately, because the fix targeted `aria-expanded` generally (https://github.com/pressbooks/pressbooks-book/pull/641/files#diff-5004549ff9223d9c89a0580f7c2b87c3L113) it introduced unwanted behavior for the table of contents as well. We should increase the specificity of the function that targets the 'download button' so that other elements with aria-expanded attributes are not impacted.

**Comment by cagp-dev-mtl** [comment]
PR for solving this issue: https://github.com/pressbooks/pressbooks-book/pull/648

This fix also addresses the arrows click event.

cc: @mcgratay

**Comment by cagp-dev-mtl** [comment]
Update: closing this PR, just noticed that clicking outside the menu does not closes it. I will fix it and re-submit the fix.
