### ISSUE TITLE
Allow user to define fixed width for embedded video when using `[embed]` shortcode

### ISSUE THREAD

**Issue by mcgratay** [pressbooks/pressbooks-book#654]
### Description

All videos in a webbook resize to 100% width in order to be responsive to readers' screen size. This overrides the widths and heights that users may have inserted if they used the `[embed]` shortcode. Though it makes sense to override pixel widths that wouldn't be responsive to reader screen size, Pressbooks should respect user values when explicitly declared in embed shortcodes. 

Example: https://videoresizingissues.textopress.com/chapter/embedded-video-tests/

`[embed width="250"]https://www.youtube.com/watch?v=Z4GMUlCBgd0[/embed]`

### Steps to Reproduce

1. Copy a YouTube video URL
2. Add a new chapter to your book in Pressbooks and create an embed shortcode with a width set to a percentage
3. Paste the video URL and close the shortcode
4. Add the URL again without the embed shortcode for comparison, then save the chapter 
5. View in webbook 

**Expected behavior:** Video sizes default to 100% but can be manually changed

**Actual behavior:** Video sizes cannot be changed

**Comment by SteelWagstaff** [comment]
Could fix by checking to see if a `%` character appears in the width param before running resize operation here: https://github.com/pressbooks/pressbooks-book/blob/318da3b3a87ee97a3092635fd70a918954237caf/assets/src/scripts/routes/single.js#L116-L127?

**Comment by paradisojr** [comment]
I'd love to see this get added back to the 'To Do' pile if it hasn't been already. ;-)

**Comment by paradisojr** [comment]
Are you all planning to put this back into the queue any time in the near future? Thanks!

**Comment by SteelWagstaff** [comment]
Hi Jim -- yes, it's at the top of our bug backlog list. We were hoping to get it done in a previous sprint, but didn't get to it. Hopefully soon!

**Comment by cagp-dev-mtl** [comment]
Thread reference to Dac's comment about this issue:

https://pressbooks.slack.com/archives/CCWPHQY83/p1577129014010200

Video objects from youtube already come with a defined width and height, the fluid fix works fine because we are resizing all videos no matter their size attributes.

width and height values inside `[embed]` tags are ignored and replaced by the defaults set by the video provider.

As Dac mentioned in the thread, it "might" be possible to override those settings when parsing the youtube object. I will scope this ticket to one day.

**Comment by SteelWagstaff** [comment]
@paradisojr We've looked into this a bit further and we cannot fix this with the embed shortcode or the oembed method. If users want to define set widths for their embedded videos, they'll have to add those parameters to the iframe element itself and paste it into the text using the text editor. Users can get the iframe shortcode for a YouTube video by visiting the video on YouTube and then clicking 'share' -> 'embed'. They'll see something like this `<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/7tqL-9z_fFA" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`
![Screenshot from 2020-06-24 15-55-11](https://user-images.githubusercontent.com/13485451/85626838-3f4fc080-b633-11ea-842c-98e6abb3b3d6.png)

If they want a different height/width combination, they can change it manually. Our resizer script (which works on oembeds) will not touch iframe elements that have these height/width values already created. Does that make sense to you?

**Comment by paradisojr** [comment]
Thanks, @SteelWagstaff. I understand. Yeah...it only ever really comes into play when/if we want to use the oEmbed method and place that video within a PB textbox or something. Faculty certainly aren't going to get bent out of shape about it, but you know me...hehe...I'm a stickler for these sorts of details when I'm building the content. We have a solid plan going forward. No worries, and thanks again!

**Comment by SteelWagstaff** [comment]
Makes sense -- I think there's a separate problem for videos in textboxes -- the resizer puts the video outside of the textbox. We'll need to file that as different bug and should be able to address fix this. Ticket coming soon.
