### ISSUE TITLE
Resized videos break expectations when placed within textboxes

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks-book#700]
We use a fluid width resizer to dynamically adjust the width of embedded videos in the Pressbooks webbook: https://github.com/pressbooks/pressbooks-book/pull/645/files. However, when videos are embedded inside of a textbox, the resizer script does not account for the added padding inside the textbox and the resulting video embed breaks user expectations. See screenshot:
![Screenshot from 2020-06-24 16-54-58](https://user-images.githubusercontent.com/13485451/85631611-788c2e80-b63b-11ea-8329-28735f30daef.png)

Or live example at https://integrations.pressbooks.network/testclone/chapter/youtube-embeds-in-textboxes/. Ideally, the embedded video would fill only the available space inside of the textbox (without overlapping any of the padding).

**Comment by cagp-dev-mtl** [comment]
PR for this fix: #701

**Comment by SteelWagstaff** [comment]
Fix works as expected for text-boxes in front-matter, back-matters, parts, and chapters. Two things to note:
1. Sizing of videos in the visual editor itself still looks unexpected:
![Screenshot from 2020-06-30 14-34-43](https://user-images.githubusercontent.com/13485451/86169193-dbb80e00-bade-11ea-8155-cba45bdfc7bb.png)
![Screenshot from 2020-06-30 14-34-26](https://user-images.githubusercontent.com/13485451/86169195-dc50a480-bade-11ea-8f31-409a6f9c81ff.png)

1. sizing is pretty bad when videos are embedded in sidebar textboxes: 
![Screenshot from 2020-06-30 14-33-29](https://user-images.githubusercontent.com/13485451/86169092-b3301400-bade-11ea-8166-14ae49d73ec0.png)
![Screenshot from 2020-06-30 14-33-19](https://user-images.githubusercontent.com/13485451/86169094-b3c8aa80-bade-11ea-9f5c-3f2214ccfa66.png)

Sample book visible at: https://integrations.pressbooks.network/videotest/

**Comment by cagp-dev-mtl** [comment]
@SteelWagstaff , as discussed this morning, there is not much we can do for # 2.

With regards to # 1, adding the fluent resizer to the tinymce editor is not as straight-forward as it seems. Tinymce has its own sets of scripts and API and the editor elements and videos are loaded after WP custom scripts are loaded. It might be possible to set a delayed event that will try to find videos after a certain number of seconds however I am not sure if that will mess or be compatible with the Tinymce editor.

**Comment by SteelWagstaff** [comment]
Thanks for update. Fix does what was expected. Will close ticket and consider work done.

**Comment by paradisojr** [comment]
Hey, @SteelWagstaff and @cagp-dev-mtl ....It seems a very similar thing is happening with embedded PhET simulations (in terms of the object overflowing the div)....Can you please take a look for me and determine whether or not this should be logged as a separate issue? A physics professor is making a HUGE overhaul on the OpenStax College Physics book and all his embeds done in the following manner `[media src="https://phet.colorado.edu/sims/html/john-travoltage/latest/john-travoltage_en.html" /]` seem to get pushed right and end up overflowing the divs in which they are placed. Note: When embedded without a div around it, the object embeds as expected. I appreciate your attention to this matter. See sample screenshots below from my sandbox: [https://pressbooks.online.ucf.edu/prodtest/chapter/chapter-1/]. 
![PhET Embed inside Textbox](https://user-images.githubusercontent.com/33466325/91516344-34c2d900-e8b9-11ea-969c-d344e5f94395.png)
![PhEt Embed without Textbox](https://user-images.githubusercontent.com/33466325/91516352-38566000-e8b9-11ea-931b-bc80b8c33d41.png)

**Comment by SteelWagstaff** [comment]
@paradisojr yes, this should be filed as a seperate issue.

**Comment by paradisojr** [comment]
@SteelWagstaff I sent an email through premium support, as Amy mentioned it would be preferable to operate through those channels. That way, I won't disrupt your workflow here on Github. ;-) ...look forward to hearing back on this one!
Thanks!
