### ISSUE TITLE
Images with alignments do not have padding because of two overlapping CSS rules

### ISSUE THREAD

**Issue by pb-amy** [pressbooks/pressbooks-book#704]
### Description

This is happening in McLuhan (and [Bradbury, as per this book](https://pressbooks.nscc.ca/nsccprinciplesofmarketing/chapter/reading-strategy-and-tactics/), and therefore, it is likely that it is happening in other themes as well.
![Screen Shot 2020-07-31 at 11 29 48 AM](https://user-images.githubusercontent.com/61845107/89050700-2799e500-d321-11ea-85f9-bc92ebf779fa.png)

There is currently an image CSS rule regarding **margins** for all images in all the different book sections:
```
.front-matter img, .part img, .chapter img, .back-matter img {
    margin: 0;
}
```
And there is also a CSS rule regarding margins on images as well when you apply an alignment on it:
```
.alignright, .alignleft {
    margin-left: 1.5em;
}
```
However, the first rule always overrides the second rule and as a result, there is never padding on images when the image is put in alignment.

There is always the option to write custom code in **Your Custom Styles** so that images with alignments will have padding, always. However, this shouldn't be an issue native to Pressbooks' core CSS.

### Steps to Reproduce

1. Write/copy a large block of text, and also, import an image. Put the image on the same line as the text. 
2. Select an alignment. Notice that in the editor, there is a margin. 
3. Now, save and preview the chapter. You will see that the margin is gone.

**Expected behavior:** Margin on the image stays regardless of alignment (without custom styles having to be added)

**Actual behavior:** Margin on the image disappears when alignment class is applied.

**Comment by ricardopressbooks** [comment]
PR: https://github.com/pressbooks/pressbooks-book/pull/710

**Comment by SteelWagstaff** [comment]
@ricardopressbooks I'm still looking into this one, but typically images w/o captions that are floated are placed inside of div elements with the alignleft and alignright classes. Images with captions are placed inside of figure elements with the same classes applied. See https://integrations.pressbooks.network/integrationtests/chapter/small-images-without-captions/ and https://integrations.pressbooks.network/integrationtests/chapter/small-images-with-captions/. In the book example Amy linked to above, the image is in a textbox and is not wrapped in a div.

**Comment by SteelWagstaff** [comment]
Upon further investigation, I've only been able to replicate this issue when images have been placed directly inside of an unclosed block element (in Amy's example the images occur before the heading element is closed, and in other cases they are placed within an unclosed paragraph). At first glance, this appears to me to be user input errors that should be fixed in the HTML rather than our theme rules, but I could be mistaken.
