### ISSUE TITLE
iFrame width issue inside of textboxes

### ISSUE THREAD

**Issue by pb-amy** [pressbooks/pressbooks-book#730]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [McLuhan](http://github.com/pressbooks/pressbooks-book/releases/latest/), and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing the issue while using this book theme?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-book) to see if your bug or enhancement is already listed?

### Description

Manually iFramed content does not respect margins of the textboxes:
![image](https://user-images.githubusercontent.com/61845107/101802046-002c0380-3add-11eb-995e-7ca283b481b9.png)

Oembeds seem to respect these margins (i.e. youtube), but as with the example above, manual iframes do not. another example has included 

### Steps to Reproduce

1. Add iframed content inside of a div

**Expected behavior:** All embeds and iFrames should respect the borders of the textbox.

**Actual behavior:** Manual iframes do not look even in the textbox because of uneven borders.

**Comment by pb-amy** [comment]
https://pressbooks.zendesk.com/agent/tickets/3163

**Comment by SteelWagstaff** [comment]
Closing. Duplicates https://github.com/pressbooks/pressbooks-book/issues/721
