### ISSUE TITLE
Many jQuery features in use are now deprecated

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks-book#751]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [McLuhan](http://github.com/pressbooks/pressbooks-book/releases/latest/), and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing the issue while using this book theme?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-book) to see if your bug or enhancement is already listed?

### Description

While working on #748, I noticed many jQuery deprecation warnings in my console:

```
JQMIGRATE: jQuery.fn.bind() is deprecated
JQMIGRATE: jQuery.fn.click() event shorthand is deprecated
JQMIGRATE: jQuery.fn.scroll() event shorthand is deprecated
JQMIGRATE: jQuery.fn.keydown() event shorthand is deprecated
JQMIGRATE: jQuery.fn.resize() event shorthand is deprecated
```

I'm using WordPress 5.7 for local development. These issues are likely related to the long-planned [jQuery update](https://css-tricks.com/wordpress-5-7-big-ol-jquery-update/). As part of updating Pressbooks for WordPress 5.7 compatibility, use of deprecated jQuery functions should be evaluated and they should be removed/replaced.

### Steps to Reproduce

1. Navigate through a book.

**Expected behavior:** No console errors.

**Actual behavior:** Many jQuery deprecation errors.

### System Information

Pressbooks: dev
McLuhan: dev
WordPress: 5.7

**Comment by SteelWagstaff** [comment]
This may help: https://github.com/jquery/jquery-migrate
