### ISSUE TITLE
Add unique ids or classes to <li> and <a> elements in automatically generated menus

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks-book#781]
### Feature Description

As a network manager, I'd like to target specific list items/links in my site menus with CSS. However, these li and a elements do not include unique ids or classes that can be reliably targeted for styling/control at a granular level. We should add unique IDs or classes to these elements. 

Pressbooks automatically includes a few menu items containing list items and links in the nav primary menu https://github.com/pressbooks/pressbooks-book/blob/fa3b8da9eac03c3d37438b8452d0ab86b80309b8/inc/helpers/namespace.php#L189-L235 
and page footer https://github.com/pressbooks/pressbooks-book/blob/fa3b8da9eac03c3d37438b8452d0ab86b80309b8/footer.php#L66-L69

**Comment by richard015ar** [comment]
The change also should be implemented in Aldine: https://github.com/pressbooks/pressbooks-aldine/blob/7635a4d94d8ad54d5cf428b8cf148e672e7d05c6/inc/helpers/namespace.php#L169

**Comment by SteelWagstaff** [comment]
Works as expected on integrations. Changes were not deployed to textopress because of Jenkins pipeline issue, but I'm assuming it will work there once pushed as well.
