### ISSUE TITLE
Add author for individual chapters in webbook TOC under the chapter.

### ISSUE THREAD

**Issue by pb-amy** [pressbooks/pressbooks-book#784]
### Feature Description

When a book has chapters written by different authors, in the PDF export, the table of contents (TOC) shows the author names below each chapter title. 
![Screen Shot 2020-08-19 at 2 20 08 PM](https://user-images.githubusercontent.com/61845107/90674403-17419f80-e227-11ea-811b-67558b66c4ac.png)

This is not the case for webbooks as seen in this screenshot below:
![Screen Shot 2020-08-19 at 2 20 56 PM](https://user-images.githubusercontent.com/61845107/90674496-350f0480-e227-11ea-8c80-d2b9bb452b2f.png)

For accessibility, crediting and navigation purposes, this is a great feature to consider - adding the authors to their respective chapters in the TOC of the webbook.

### Feature Use Case

As stated above, this would have no drawbacks. It would credit the author more visibly, make chapters easier to navigate (finding based on author) as well as more accessible. 

### Other Notes

For internal purposes, this idea was brought up in [this ticket](https://pressbooks.zendesk.com/agent/tickets/1795).

**Comment by SteelWagstaff** [comment]
Authors should be added here: https://github.com/pressbooks/pressbooks-book/blob/dev/partials/content-toc.php. Styling will need to be looked at for the webbook home page and the block reading toc: https://github.com/pressbooks/pressbooks-book/blob/dev/assets/src/styles/components/_toc.scss

**Comment by SteelWagstaff** [comment]
Tested and working as expected on integrations
