### ISSUE TITLE
Images without captions don't align properly

### ISSUE THREAD

**Issue by beckej13820** [pressbooks/pressbooks-book#792]
### Description

When a image doesn't have a caption, it doesn't float left or right (or align center) properly.

### Steps to Reproduce

1. put three images in a book in different locations without captions
3. float one image left, float one image right, and choose align center for the third image
3. make sure it is formatting properly in the webbook.
4. export to EPUB and PDF using printPDF, or digitalPDF

**Expected behavior:** 

I would expect consistent formatting across exports.

**Actual behavior:** 

When there is no caption, the image appears inline with the line on the page. I can correct the issue by adding a caption, and removing the caption returns the images to inline format. 

Screenshots below:
The first screenshot is from the webbook, and shows what we are trying to accomplish.
<img width="1195" alt="Screen Shot 2019-07-15 at 6 09 59 PM" src="https://user-images.githubusercontent.com/29982981/61253218-3c173980-a72e-11e9-9850-26f778cadb1c.png">
This image shows a series of images in a PDF export that aren't being floated properly left or right. All of the images don't have captions.
<img width="750" alt="Screen Shot 2019-07-15 at 6 15 08 PM" src="https://user-images.githubusercontent.com/29982981/61253153-feb2ac00-a72d-11e9-90e2-d9d14808be46.png">
This next image shows that when I add a caption to the images, it will align in the export formats.
<img width="746" alt="Screen Shot 2019-07-15 at 6 14 59 PM" src="https://user-images.githubusercontent.com/29982981/61253188-1c801100-a72e-11e9-9594-e91c69e918e5.png">

Removing the captions returns it back to an inline image without the float.

**Comment by SteelWagstaff** [comment]
Tested on integrations and works as expected!

**Comment by gavinpressbooks** [comment]
Tested on integrations using https://integrations.pressbooks.network/usaskphystest/chapter/image-test/. Tested on PDF, EPUB and MOBI export formats. Webbook, PDF and EPUB exports are behaving as expected (EPUB files were tested using the Apple Books app and Adobe Digital Editions). 

The only unusual behavior I saw was with MOBI exports—viewing the export on the Kindle iOS app showed the same inline position issue but viewing the same MOBI file on a 3rd party ebook viewer shows the issue as fixed (see attached screenshots below).

<img width="1157" alt="PDF export" src="https://user-images.githubusercontent.com/85123231/123841118-2d0b0100-d8dd-11eb-9d3b-658b0e4cd962.png">
<img width="1581" alt="EPUB Apple Books" src="https://user-images.githubusercontent.com/85123231/123841155-372cff80-d8dd-11eb-808f-c8cef00bc290.png">
<img width="1539" alt="EPUB Adobe Digital Editions" src="https://user-images.githubusercontent.com/85123231/123841167-3ac08680-d8dd-11eb-8604-801d790331ff.png">
![MOBI kindle iOS app](https://user-images.githubusercontent.com/85123231/123841191-414efe00-d8dd-11eb-9cd3-7e9b4e83f8e4.jpeg)
![MOBI 3rd party reader](https://user-images.githubusercontent.com/85123231/123841202-4449ee80-d8dd-11eb-9aeb-b09934134b03.jpg)

**Comment by gavinpressbooks** [comment]
Find below the MOBI screenshots. 1) Kindle iOS app, 2) 3rd party reader
![MOBI kindle iOS app](https://user-images.githubusercontent.com/85123231/123841693-dd790500-d8dd-11eb-9ada-1fea4aa9fc24.png)
![MOBI 3rd party reader](https://user-images.githubusercontent.com/85123231/123841704-e10c8c00-d8dd-11eb-89a2-6c639f9c2ebc.png)
