### ISSUE TITLE
Webbook displays contributor's first name and last name values instead of name

### ISSUE THREAD

**Issue by thomasdumm** [pressbooks/pressbooks-book#833]
### Description

When you're creating a contributor for your book, you can enter a name, as well as a first name and last name. Name is the only required field. When you enter a name value which differs from the values entered for first name and last name, as when a user has a title, honoric, or multiple names, the webbook displays the contributor as 'first name' + 'last name' on the webbook home page and chapter author displays, even though 'name' is the better/expected field.

### Steps to Reproduce

1. Create a contributor whose name value differs from 'first name' + 'last name'
![Screenshot from 2021-08-12 15-06-42](https://user-images.githubusercontent.com/13485451/129276329-cdd29eea-6155-438b-a823-92b503e0ada8.png)

2. Assign this contributor as the author of a chapter
![Screenshot from 2021-08-12 15-09-14](https://user-images.githubusercontent.com/13485451/129276326-550f9783-5579-4203-8b4c-a772caa27e0f.png)
3. View the chapter in webbook and observe that the author's first name+last name is displayed rather than their name value
![Screenshot from 2021-08-12 15-15-27](https://user-images.githubusercontent.com/13485451/129276923-635aabc3-692b-4e45-a455-d2c54e7a0dcc.png)
4. View the chapter in the organize menu and observe that the author's first name+last name is displayed rather than their name value
![Screenshot from 2021-08-12 15-09-24](https://user-images.githubusercontent.com/13485451/129276325-2b3c3798-6793-47a9-8b14-ccc500ee9350.png)
5. Add this contributor to the book's book info page as an author
![Screenshot from 2021-08-12 15-16-34](https://user-images.githubusercontent.com/13485451/129277012-d50c887f-62f2-427d-81af-158614b646c0.png)
6. Visit the webbook home page and observe that the author's first name+last name is displayed rather than their name value
![Screenshot from 2021-08-12 15-08-43](https://user-images.githubusercontent.com/13485451/129276328-5b4916f4-12ab-419c-a8db-5c0f6b962f08.png)
![Screenshot from 2021-08-12 15-23-56](https://user-images.githubusercontent.com/13485451/129277605-b96cadae-ddd1-4f11-952d-346a00562e20.png)
![Screenshot from 2021-08-12 15-23-45](https://user-images.githubusercontent.com/13485451/129277608-19e7f359-67ad-435d-93e1-c427f7d8871a.png)
 
**Expected behavior:** 
name is used for contributor
**Actual behavior:** 
first name and last name are used for contributor

## notes from original reporter
Reason: In the name field I can naturally add titles (like Prof. Dr.) which would be strange to add to firstname or lastname field. The contributor should appear with titles (like Prof. Dr.) in the webbook.

![contributor](https://user-images.githubusercontent.com/3658808/53090270-28fd9600-350f-11e9-9359-b9ce530593c6.JPG)
![web](https://user-images.githubusercontent.com/3658808/53090271-28fd9600-350f-11e9-9817-740988e9266b.JPG)

**Comment by SteelWagstaff** [comment]
We've added new prefix and suffix fields for contributors. If the contributor has a name but no prefix, first name, last name, or suffix values, it will display their name. If they do have values for prefix, first name, last name, and/or suffix, these values will be preferred/displayed. Once this feature is released, to fix the 'bug', users can simply add new prefix/suffix values for these contributors.
