### ISSUE TITLE
Contributors Fixes

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks-book#848]
Before releasing the new contributors feature, we need to do the following:

- [x] Set up automatic singular/pluralization for 'About the author' block on individual chapters: https://github.com/pressbooks/pressbooks-book/blob/a285832e9aab0bbafb7fcf625269063b4d70515c/partials/content-single.php#L71 
If there's just one author, display 'About the Author' as the heading. If there are 2 or more, display 'About the Authors'
- [x] Create a Contributor back matter type available to all books, so that existing books can create auto generated contributor pages: https://github.com/pressbooks/pressbooks/blob/59df8e28d66972f144e2a5c284f65929b5d9d25e/inc/class-taxonomy.php#L424-L428 (I think the issue here may be that the 'Contributors' slug is already in use elsewhere?)
- [ ] Make sure all contributor information is included when books/contributors are cloned (might need PR in Pressbooks?)
- [x] Change the display name of the default WordPress 'Contributor' role to 'Collaborator'. See https://wordpress.org/support/article/roles-and-capabilities/ for more on roles & capabilities within WordPress and https://wpmudev.com/blog/change-wordpress-role-names/ for one approach.

**Comment by arzola** [comment]
Some notes:

1. I feel using the pluralization function in this case is not needed we have to count the $authors length and then print the static value, we can save a function import/call doing something like: `$authors_title = count( $authors ) > 1 ? 'Author' : 'Authors'` will be better than `$authors_title = count( $authors ) > 1 ? 'Author' : Str::pluralize('Author')`

**Comment by SteelWagstaff** [comment]
To fix cloning routine, we should probably add contributors to get book terms: https://github.com/pressbooks/pressbooks/blob/d712117757f36503505e61e85a82fa13acdc980b/inc/cloner/class-cloner.php#L859 and then make sure we’re not overriding them with the get book info names (consider removing/altering this block: https://github.com/pressbooks/pressbooks/blob/d712117757f36503505e61e85a82fa13acdc980b/inc/cloner/class-cloner.php#L1317-L1321). Once we do this, we still need to clone book info, but can remove the ‘create contributor’ step.

**Comment by SteelWagstaff** [comment]
Created https://github.com/pressbooks/pressbooks/issues/2358 to track cloning issue. All other work in this ticket is done and tested on integrations.
