### ISSUE TITLE
'Where to click' on mobile for "metadata" and "book information"

### ISSUE THREAD

**Issue by pb-amy** [pressbooks/pressbooks-book#913]
### Feature Description

On mobile the "Metadata" and "Book information" fields on the webbook homepage are collapsed and just show the heading. A user can tap the header to expand the field a display the hidden information. To see this, try any book (ex: https://university.pressbooks.pub/oerstarterkit/)

https://user-images.githubusercontent.com/13485451/146303780-f32d5c9c-207f-47ee-a5bb-2afa1c7e84db.mp4

It's not intrinsically clear that there is hidden information here or that the user can tap the header to have the field expand. This is confusing to many visitors. We should either expand these sections by default in mobile view or include a visual indicator of 'where to click' so that users can know to tap on the header to see what's within Metadata and Book information sections.

### Feature Use Case

It would impact all mobile book users for the better; it would help visibility of these fields, and would only improve navigation.

### Other Notes

Code which does this is here: https://github.com/pressbooks/pressbooks-book/blob/3890e70dc660eb3d25d81fa22cae91887d80f6f7/partials/content-cover-metadata.php#L5 
https://github.com/pressbooks/pressbooks-book/blob/3890e70dc660eb3d25d81fa22cae91887d80f6f7/partials/content-cover-book-info.php#L3 
https://github.com/pressbooks/pressbooks-book/blob/3890e70dc660eb3d25d81fa22cae91887d80f6f7/packages/aetna/assets/styles/layouts/_page-sections.scss#L89-L95

**Comment by fdalcin** [comment]
Tested on integrations and works as expected
![image.png](https://images.zenhubusercontent.com/60a7e6a889e8274a68d8c65b/48fed367-7887-4e55-9550-604456f71fc6)
