### ISSUE TITLE
Add support for Cherokee using Language & Script Support

### ISSUE THREAD

**Issue by tw77** [pressbooks/pressbooks-book#960]
### Description
As an author, I'd like to be able to include glyphs from the Unicode block for the Cherokee alphabet in my Pressbooks exports. Pressbooks includes a Language & Script support feature which allows book authors to include noto fonts for several languages & scripts. We should add Cherokee to this list by adding support for Noto Sans Cherokee: https://notofonts.github.io/noto-docs/specimen/NotoSansCherokee/

Characters from the Unicode block [Cherokee](https://www.unicode.org/charts/PDF/U13A0.pdf), which contains syllabic characters for writing the Cherokee language, do not render in exported PDFs. (EPUBs and webbooks are fine.)

Replicated with Malala and McLuhan themes. Appears to be unrelated to font: changing the body font in PDF Options from the theme default to a serif alternative (Cormorant Garamond) or a sans serif alternative (Raleway) has no effect.

_Text editor_
<img width="752" alt="text" src="https://user-images.githubusercontent.com/44182629/152816812-fdcd8251-95a8-4acd-b599-80490407b3b1.png">

_Webbook_
<img width="132" alt="web" src="https://user-images.githubusercontent.com/44182629/152816742-1a78ef40-2814-4170-8be4-29fca6122b3a.png">

_PDF output_
<img width="213" alt="pdf" src="https://user-images.githubusercontent.com/44182629/152816876-496f0bb5-d285-4de1-a4b1-ec74f4e175a9.png">

Reported here: https://pressbooks.zendesk.com/agent/tickets/9078

### Steps to Reproduce

1. Use any character from the Unicode block [Cherokee](https://www.unicode.org/charts/PDF/U13A0.pdf) in a book chapter, for example Ꮖ
2. Save the chapter.
2. Confirm that the character(s) appear correctly in the webbook.
3. Export the book and view the chapter with the character(s).

**Expected behavior:** The characters render.

**Actual behavior:** A ? symbol appears instead of the characters.

**Comment by SteelWagstaff** [comment]
We might need to add support for Cherokee to our Language & Script support option. This would entail adding the Noto Cherokee families to our project: https://notofonts.github.io/noto-docs/specimen/NotoSansCherokee/. See https://github.com/pressbooks/pressbooks-book/issues/585 for previous issue with Adlam/N'Ko as model.

**Comment by SteelWagstaff** [comment]
Tested and working as expected in https://integrations.pressbooks.network/sprintreview

Screenshots showing bold and regular characters in EPUB and PDF included below:
![Screenshot from 2022-04-05 11-49-54](https://user-images.githubusercontent.com/13485451/161828355-e1731c10-a7aa-47f4-a02f-98cc5b8b29c7.png)
![Screenshot from 2022-04-05 11-49-46](https://user-images.githubusercontent.com/13485451/161828358-1c62cc7c-95ee-4e48-bc6d-8458d9795e5e.png)
