### ISSUE TITLE
Adding custom styles below the McLuhan web-Theme has no effect

### ISSUE THREAD

**Issue by thomasdumm** [pressbooks/pressbooks-book#97]
### Prerequisites

_Check the boxes below by changing them from `[ ]` to `[x]`._

* [x] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [Pressbooks Book](http://github.com/pressbooks/pressbooks-book/releases/latest/), and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing the issue while using this book theme?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-book) to see if your bug or enhancement is already listed?

### Description
 I added the following below the McLuhan web-Theme without seeing an effect on the web book:

$section-title-align: left !default;
$section-subtitle-align: left !default;
$h1-align: left !default;
$h2-align: left !default;
$h3-align: left !default;
$h4-align: left !default;
$h5-align: left !default;
$h6-align: left !default;

$color-1: (
  epub: initial,
  prince: initial,
  web: red
) !default;

#### Book Info

Book ID: 6
Book URL: http://localhost/wordpress/pwlo00117r7/
Book Privacy: Public

#### Browser

Platform: OS X
Browser Name: Firefox
Browser Version: 58.0
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:58.0) Gecko/20100101 Firefox/58.0

#### WordPress Configuration

Network URL: http://localhost/wordpress/
Network Type: Subdirectory
Version: 4.9.4
Language: en_US
WP_ENV: developer
WP_DEBUG: Enabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 4.5.0
Book Theme: McLuhan
Book Theme Version: 2.0.0-alpha1
Root Theme: Aldine
Root Theme Version: 1.0.0-alpha.6

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

Pressbooks: 5.0.0-dev

#### Server Configuration

PHP Version: 7.1.12
MySQL Version: 5.6.38
Webserver Info: Apache/2.2.34 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.1.12 mod_ssl/2.2.34 OpenSSL/1.0.2j DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.24.0

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 256M
Upload Max Size: 32M
Post Max Size: 32M
Upload Max Filesize: 32M
Time Limit: 30
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: On (1)

#### PHP Extensions

OPcache: Disabled
XDebug: Disabled
cURL: Supported
cURL Version: 7.52.1
imagick: Not Installed
xsl: Installed

**Comment by greatislander** [comment]
Are you using [Custom Styles](https://guide.pressbooks.com/chapter/customizing-your-exports-with-custom-styles/)? That feature cannot be used in the way you are trying to use it; SCSS variables have to be overridden above the theme's stylesheets. Please clarify, thanks!

**Comment by thomasdumm** [comment]
![yourstyles](https://user-images.githubusercontent.com/3658808/35980003-f3a1d852-0ce9-11e8-99b3-4db213e1875e.jpg)

**Comment by thomasdumm** [comment]
I did the above. I did not fully understand your comment. can you please give me an example how I would text-align all headings left?
